select * from GXBDBPS.AUPRCCDE 
 WHERE PRCDTRNTYP =40        
 
select * from libdebito.embnov0d 
 WHERE PRCDTRNTYP =40           
 
SELECT * FROM GXFINDTA.TCLVCT WHERE VCTFHULTUP >= '2020-09-24 00:00:00' AND VCTFHULTUP <= '2020-09-24 23:59:59';
   

SELECT COCOMER, CODENO,CORUCN, ENEMISO, ADNUMCTA,COFECALT,COFULMOD FROM GXBDBPS.COMAEAF
WHERE ADNUMCTA IN(SELECT VCTNCTAFT FROM GXFINDTA.TCLVCT WHERE VCTFHULTUP >= '2020-09-24 00:00:00' AND VCTFHULTUP <= '2020-09-24 23:59:59');

-- verificaciones comaexd y comaext post implementacion

SELECT * FROM GXBDBPS.COMAEXT WHERE CECTABAN = '' AND SUBSTR(COCOMER,1,2) <> '45' AND BPSSRVCOD IN( 1,2,3,4,5,9);

SELECT * FROM yapi.COMAEXT WHERE CECTABAN = '' AND SUBSTR(COCOMER,1,2) <> '45' AND BPSSRVCOD IN( 1,2,3,4,5,9);

SELECT C.COCOMER, C.ENEMISO, C.adticta,C.ADNUMCTA,C.rprecod,S.COCOMER,S.CECODBAN,S.CETIPCTA,S.CECTABAN,S.RPRECODI,S.CEUSRM
FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXT AS S
ON C.COCOMER = S.COCOMER  
AND S.BPSSRVCOD IN( 1,2,3,4,5,9)
AND S.CEUSRM = 'MIGRACION'
and c.cocomer in ('0100170',
'0200890',
'0302271',
'0302284');



SELECT COCOMER,ENEMISO FROM GXBDBPS.COMAEAF WHERE COCOMER in 
('0100170',
'0200890',
'0302271',
'0302284');


SELECT * FROM CONTABILID.TATGENE WHERE TGENTI in('055', '054', '057');

SELECT * FROM GXBDBPS.COMAEXD WHERE CCMTASA = 0 AND CCTIPTA = 'D' AND BPSSRVCOD IN( 1,2,3,4,5,9) AND SUBSTR(COCOMER,1,2) <> '45'
SELECT * FROM yapi.COMAEXD WHERE CCMTASA = 0 AND CCTIPTA = 'D' AND BPSSRVCOD IN( 1,2,3,4,5,9) AND SUBSTR(COCOMER,1,2) <> '45';


SELECT * FROM GXBDBPS.COMAEAF WHERE COCOMER='8102652'
SELECT * FROM GXBDBPS.COMAEXD WHERE COCOMER='0703634' AND BPSSRVCOD='2'

SELECT * FROM GXBDBPS.COMA1AF WHERE COCOMER='0703634' AND BPSSRVCOD='2'

SELECT C.COCOMER, C.ADDESCRE,S.COCOMER,S.CCMTASA,S.CCUSRM FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'C' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRM = 'MIGRACION';

SELECT C.COCOMER, C.ADDESDEB,S.COCOMER,S.CCMTASA,S.CCUSRM FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'D' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRM = 'MIGRACION';


-- vER COMERCIOSQUE NO TENIAN SERVICIO

SELECT COCOMER,costat,COFECALT,COFULMOD FROM GXBDBPS.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = 1) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78';

SELECT COCOMER,costat,COFECALT,COFULMOD FROM yapi.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM yapi.COMAEXT WHERE BPSSRVCOD = 1) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78';


SELECT * FROM GXBDBPS.COMAEXT WHERE CEUSRA = 'MIGRACION' and CEFECA = '20201027' and BPSSRVCOD = '1';
SELECT * FROM yapi.COMAEXT WHERE CEUSRA = 'MIGRACION' and CEFECA = '20201027' and BPSSRVCOD = '1';



SELECT * FROM GXBDBPS.COMAEXD WHERE CCUSRA = 'MIGRACION' and CCFECA = '20201027' and BPSSRVCOD = '1';
SELECT * FROM yapi.COMAEXD WHERE CCUSRA = 'MIGRACION' and CCFECA = '20201027' and BPSSRVCOD = '1';


--credito
SELECT C.COCOMER, C.ADDESCRE,S.COCOMER,S.CCMTASA,S.CCUSRM, S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'C' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '1' AND S.CCMARCA = 'DIN';
--debito
SELECT C.COCOMER, C.ADDESDEB,S.COCOMER,S.CCMTASA,S.CCUSRM,  S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'D' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION'AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '1' AND S.CCMARCA = 'DIN';


SELECT C.COCOMER, C.ADDESCRE,S.COCOMER,S.CCMTASA,S.CCUSRM, S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'C' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '1' AND S.CCMARCA = 'DIN';



select * from gxbdbps.comaexd where BPSSRVCOD = '1' and CCMTASA = 0 AND SUBSTR(COCOMER,1,2) <>'45';
select * from gxbdbps.comaeaf where cocomer = '6900306';




SELECT COCOMER,COPRCODI FROM GXBDBPS.COMA1AF WHERE COCOMER IN( SELECT COCOMER FROM GXBDBPS.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = 2) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78' )
AND PRCODI = '995';

SELECT COCOMER,COPRCODI FROM yapi.COMA1AF WHERE COCOMER IN( SELECT COCOMER FROM yapi.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM yapi.COMAEXT WHERE BPSSRVCOD = 2) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78' )
AND PRCODI = '995';


SELECT * FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = '2' AND CEUSRA = 'MIGRACION' and CEFECA = '20201027';

SELECT * FROM CONTABILID.TATGENE WHERE TGCODE = 'BF';


SELECT C.COCOMER, C.ADDESCRE,S.COCOMER,S.CCMTASA,S.CCUSRM,  S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'C' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '2' and C.COCOMER in (
'0302278',
'0302303',
'0700992',
'0701675',
'0701962');
--debito
SELECT C.COCOMER, C.ADDESDEB,S.COCOMER,S.CCMTASA,S.CCUSRM,  S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'D' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '2' and C.COCOMER in (
'0302278',
'0700992');

8100483 0700992 50
8101875 0302278 40

select * from gxbdbps.comaeaf where cocomer in(
select * from gxbdbps.coma1af where COCOMER in (
'0302278',
'0302303',
'0700992',
'0701675',
'0701962'
) and prcodi = '995');



SELECT * FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = '2' AND CEUSRA = 'MIGRACION' and CEFECA = '20201022';


SELECT * FROM GXBDBPS.COMAEXD WHERE COCOMER='0700992'



-- RED DE PAGOS


SELECT COCOMER,COPRCODI FROM GXBDBPS.COMA1AF WHERE COCOMER IN( SELECT COCOMER FROM GXBDBPS.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = 2) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78' )
AND PRCODI = '994';

SELECT COCOMER,COPRCODI FROM yapi.COMA1AF WHERE COCOMER IN( SELECT COCOMER FROM yapi.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM yapi.COMAEXT WHERE BPSSRVCOD = 2) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78' )
AND PRCODI = '994';


SELECT * FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = '3' AND CEUSRA = 'MIGRACION' and CEFECA = '20201027';



SELECT C.COCOMER, C.ADDESCRE,S.COCOMER,S.CCMTASA,S.CCUSRM,  S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'C' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '3' and C.COCOMER in (
'0302278',
'0302303',
'0700992',
'0701675',
'0701962');

--debito
SELECT C.COCOMER, C.ADDESDEB,S.COCOMER,S.CCMTASA,S.CCUSRM,  S.BPSSRVCOD, S.CCMARCA FROM GXBDBPS.COMAEAF AS C INNER JOIN GXBDBPS.COMAEXD AS S
ON C.COCOMER = S.COCOMER AND S.CCTIPTA = 'D' 
AND SUBSTR(S.COCOMER,1,2) <> '45'
AND S.CCUSRA = 'MIGRACION' AND S.CCFECA = '20201027' AND S.BPSSRVCOD = '3' and C.COCOMER in (
'0302278',
'0302303',
'0700992',
'0701675',
'0701962');

select * from gxbdbps.comaeaf where cocomer in(
select * from gxbdbps.coma1af where COCOMER in (
'0302278',
'0302303',
'0700992',
'0701675',
'0701962'
) and prcodi = '994');



SELECT * FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = '3' AND CEUSRA = 'MIGRACION' and CEFECA = '20201027';

SELECT COCOMER,COPRCODI FROM GXBDBPS.COMA1AF WHERE COCOMER IN( SELECT COCOMER FROM GXBDBPS.COMAEAF WHERE NOT COCOMER IN(SELECT COCOMER FROM GXBDBPS.COMAEXT WHERE BPSSRVCOD = 1) AND COSTAT in(1,0)
AND NOT SUBSTR(COCOMER,1,2)IN('45','65') AND SUBSTR(COCOMER,1,2)<= '78' )
AND PRCODI = '994';



SELECT * FROM GXBDBPS.COMAEXT WHERE COCOMER='6900306'
DELETE GXBDBPS.COMAEXT WHERE COCOMER='6900306'

SELECT * FROM GXBDBPS.COMAEXD WHERE CCMTASA='0' AND COCOMER='6900306'
DELETE GXBDBPS.COMAEXD WHERE COCOMER='6900306'

6900306

SELECT * FROM GXBDBPS.COMAEXT WHERE COCOMER='0703634' AND BPSSRVCOD='2'
DELETE GXBDBPS.COMAEXT WHERE COCOMER='0703634' AND BPSSRVCOD='2'
SELECT * FROM GXBDBPS.COMAEXD WHERE COCOMER='0703634' AND BPSSRVCOD='2'
DELETE GXBDBPS.COMAEXD WHERE COCOMER='0703634' AND BPSSRVCOD='2'



SELECT * FROM GXBDBPS.COMAEAF WHERE COCOMER='8602120' 

SELECT * FROM GXBDBPS.TCOMAR

SELECT * FROM GXBDBPS.TCOMPR
