delete from sifen.autofacturaelectronica where idempresa >0 and idde >0;
delete from sifen.pagocheque ;
delete from sifen.condicionoperacionpagocontado where idempresa >0 and idde >0;
delete from sifen.condicionoperacionpagocreditocuota where idempresa >0 and idde >0;
delete from sifen.condicionoperacionpagocredito where idempresa >0 and idde >0;
delete from sifen.condicionoperacion where idempresa >0 and idde >0;
delete from sifen.documentoasociado where idempresa >0 and idde >0;
delete from sifen.documentoelectronicofueradefirma  where idempresa >0 and idde >0;
delete from sifen.itemoperaciondescuento  where idempresa >0 and idde >0;
delete from sifen.itemoperacionprecio  where idempresa >0 and idde >0;
delete from sifen.itemoperacioniva  where idempresa >0 and idde >0;
delete from sifen.itemoperacionrastreomercaderia ;
delete from sifen.itemoperacion  where idempresa >0 and idde >0;
delete from sifen.complementocomercialgeneral ;
delete from complementocomercialseguropoliza ;
delete from complementocomercialseguro ;
delete from sifen.complementocomercial ;
delete from sifen.especificodecampo  where idempresa >0 and idde >0;
delete from sifen.notacredebelectronica  where idempresa >0 and idde >0;
delete from sifen.transportemercaderialocalentrega  where idempresa >0 and idde >0;
delete from sifen.transportemercaderialocalsalida  where idempresa >0 and idde >0;
delete from sifen.transportemercaderiatransportista  where idempresa >0 and idde >0;
delete from sifen.transportemercaderiatransportista  where idempresa >0 and idde >0;
delete from sifen.transportemercaderiavehiculotraslado  where idempresa >0 and idde >0;
delete from sifen.transportemercaderia  where idempresa >0 and idde >0;
delete from sifen.notaremisionelectronica  where idempresa >0 and idde >0;
delete from sifen.especificode  where idempresa >0 and idde >0;
delete from sifen.generaldeemisor  where idempresa >0 and idde >0;
delete from sifen.generaldereceptor  where idempresa >0 and idde >0;
delete from sifen.operacioncomercial  where idempresa >0 and idde >0;
delete from sifen.generalde  where idempresa >0 and idde >0;
delete from sifen.loteeventoresp  where idempresa >0 and idlote  >0;
delete from sifen.lotedetalleeventorespmensaje  where idempresa >0 and idde >0 and idlote  >0;
delete from sifen.lotedetalleeventoresp  where idempresa >0 and idde >0 and idlote  >0;
delete from sifen.lotedetalleevento  where idempresa >0 and idde >0 and idlote  >0;
delete from sifen.operacionde  where idempresa >0 and idde >0 ;
delete from sifen.timbrado  where idempresa >0 and idde >0 ;
delete from sifen.documentoelectronicototal  where idempresa >0 and idde >0 ;
delete from sifen.documentoelectronicoevento  where idempresa >0 and idde >0 ;
delete from sifen.documentoelectronico  where idempresa>0 and idde >0;
delete from integracion.dto ;

delete from loteevento ;
delete from lote;
