------------------------------------------------------------------DINELCO MOVIL---------------------------------------------------------------------------------------------------------
SELECT * FROM GXDEBITO.TGENVMSG--TGENVMSG
SELECT * FROM GXDEBITO.TGENVMSGH WHERE AM1CIP LIKE '%3303119'
select * from gxdebito.TGSVBEP WHERE CLIENTMV LIKE '%0982451451%'--'%983641376%' -- TABLA DINELCO MOVIL
--NUEVAS TABLAS - REINGENIERIA - DINELCO MOVIL--
select * from gxswtdta.tdmserv; -- descripcion de tipo servicio
select * from gxswtdta.tdmenser;
select * from gxswtdta.tdmacbnf;
select * from gxswtdta.TDMPRSRV WHERE PRSRTEL = '0982451451'; --TABLA DINELCO MOVIL NUEVA
select * from gxswtdta.TDMTXSRV;
select * from gxswtdta.TDMAUD;
select * from gxswtdta.TDMAUDDT;
SELECT --*
LFCOTR FECHA_CIAL, LFECTR FECHA_REAL, LHORTR HORA, LIDCOM COD_COM, LCOMTR COMERCIO, SUBSTR(LNRTAR,1,6) || 'XXXXXX' ||SUBSTR(LNRTAR,13,4) TARJETA, LCODBC MARCA, LIMPGS IMPORTE, LCRETR RETORNO,
LESTTR ESTADO, LCAUTR AUTORIZACION, LERRNB REFERENCIA, LIDTRA ID_TRX, LCODTR COD_TRX, TXDTRX TIPO_TRX, LECA62 DISPOSITIVO, LACTFJ ACT_FIJO, LCORED RED, LCOTEL LINEA_ORIGEN, LNTOKE LINEA_DESTINO, LENEMI EMISOR, LSALTR, LDISTR
FROM LIBDEBITO.DRCONBEP
INNER JOIN LIBDEBITO.TBCTRA0P ON (TXCTRX=LCODTR)
WHERE LCODTR='304010' AND LCOTEL='0982451451' --AND LFECTR='20210629' --- CONSULTA DE SALDO CIBERSONS
ORDER BY LFECTR DESC, LHORTR DESC;
SELECT * FROM LIBDEBITO.LINPORTA WHERE LNUMER LIKE '%982451451%'
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- TABLA DINELCO MOVIL - VIEJO -- 138344 reg
SELECT ID, CLIENTID CI_NRO, CLIENTMV CEL_NRO, CLIENTUP FECHA_ALTA, COMPMIN COMPRA_MIN, PAGFACT PAGO_FACT, CONSSAL CONS_SALDO, SMSTRAN SMS_TRX, UPUSER USER_ALTA, /*TGSVEND VENDEDOR,*/ FECMODI FECHA_MODIF, USERMO USER_MODIF
FROM GXDEBITO.TGSVBEP
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- TABLA DINELCO MOVIL - NUEVO -- 85792 reg
SELECT PRSRDOC DOC_NRO, a.SERVID ID_SERVICE, b.SERVDESC DESCRIP_SERVICE, ENSERENT ENTIDAD, /*PRSRTRJ TARJETA,*/ PRSRADH ADHERENCIA, PRSRTEL TELF, PRSRESTR, PRSRESTS ESTADO, PRSRFCHA FECHA, PRSRUSM USER_MODIF, PRSRFCHM FECHA_MODIF
FROM GXSWTDTA.TDMPRSRV a
INNER JOIN gxswtdta.tdmserv b ON b.SERVID=a.SERVID
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT ID, CLIENTID CI_NRO, CLIENTMV CEL_NRO, CLIENTUP FECHA_ALTA, COMPMIN COMPRA_MIN, PAGFACT PAGO_FACT, CONSSAL CONS_SALDO, SMSTRAN SMS_TRX, UPUSER USER_ALTA,
FECMODI FECHA_MODIF, USERMO USER_MODIF, a.SERVID ID_SERVICE, b.SERVDESC DESCRIP_SERVICE, ENSERENT ENTIDAD, PRSRESTS ESTADO, PRSRFCHA FECHA, PRSRUSM USER_MODIF, PRSRFCHM FECHA_MODIF, SUBSTR(PRSRTRJ,1,6) || 'XXXXXX' ||SUBSTR(PRSRTRJ,13,4) TARJETA
FROM GXDEBITO.TGSVBEP x
LEFT JOIN GXSWTDTA.TDMPRSRV a ON PRSRDOC=CLIENTID AND CLIENTMV=PRSRTEL
LEFT JOIN gxswtdta.tdmserv b ON b.SERVID=a.SERVID
