----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PASOS PARA DESCARGAR MANUALMENTE LOS T113:
#1 DESCARGAR EL T113 DESDE EL SITCEVO (BULK)
#2 EJECUTAR EL PGM PARA FORMATEAR: CALL PGM(MASTERCARD/MAIP113R) PARM('T113105762' 'ICA19696  ' 'P' '00')
#3 EJECUTAR INSERCION:
INSERT INTO GXBDBPS.IPMFCTL
(IPMFCNAME ,IPMFCINS ,IPMFCSTS ,IPMFCULTP ,IPMFDWNL ,IPMFUPDWN ,IPMFCMEMB ,BULKID ,IPMFBRECQ ,IPMFFECPRO,IPMESTEJE ,IPMUSUUPD)
VALUES
('T113108204', VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'PRC', NOW(), 'S', 'DWL', 'ICA19696', 'T113108204',
(SELECT CAST(COUNT(*) AS DEC(8, 0)) FROM GXBDBPS.IPMDTATE y WHERE y.IPMFNAME = 'T113108204' AND y.IPMDELN =2) , VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'S', 'MASTRUSR')
#4 EJECUTAR QUERY PARA SACAR PLANILLA DE RECHAZADOS:

WITH IRD AS (
SELECT
w.IPMFNAME,
w.IPMARN,
w.IPMDELN,
(SELECT CAST(SUBSTR(w1.IPMTDEV, 1 , 19) AS CHAR(19))
FROM GXBDBPS.IPMDTATE w1
WHERE w1.IPMARN = w.IPMARN AND w1.IPMDELN = 2 LIMIT 1) TARJETA,
(SELECT w2.CCA40 FROM GXBDBPS.MPE0040 w2
where
EXISTS (SELECT 1
FROM GXBDBPS.IPMDTATE w1
WHERE
w1.IPMARN = w.IPMARN AND w1.IPMDELN = 2 AND
(substr(w2.iarl40, 1, 6)) = (SUBSTR(w1.IPMTDEV, 1 , 6))) LIMIT 1) PAIS,
(SELECT CAST(SUBSTR(w1.IPMTDEV, 1 , 5) AS CHAR(4))
FROM GXBDBPS.IPMDTATE w1
WHERE w1.IPMARN = w.IPMARN AND w1.IPMDELN = 26 LIMIT 1) MCC,
CAST ( SUBSTR(TRIM(IPMTDEV), 1, 3) AS CHAR(3)) PRODUCTO,
CAST((SELECT SUBSTR(w1.IPMTDEV, 39 , 2) CONCAT CHAR(CAST(RRN(w1) AS DEC(10, 0)))
FROM GXBDBPS.IPMDTATE w1
WHERE w1.IPMARN = w.IPMARN AND
w1.IPMDELN = 48 LIMIT 1) AS CHAR(12)) IRD
FROM GXBDBPS.IPMDTATE w
WHERE w.IPMFNAME IN ('T113130147','T113130148','T113130192','T113130193') AND
--WHERE w.IPMFNAME ='T113114010' AND
w.IPMMTI = 1240 AND
w.IPMFNC = 200 AND
w.IPMDELN = 63)
SELECT
p.IPMFNAME "ARCHIVO",
p.TARJETA "TARJETA",
P.PAIS "PAIS",
p.MCC,
p.IPMARN "ARN DE LA TRX",
p.IPMDELN "DATA ELEMENT",
p.PRODUCTO "PRODUCTO",
CAST(SUBSTR(p.IRD, 1, 2) AS CHAR(2)) "IRD ACTUAL",
CAST(
CASE
WHEN p.PRODUCTO = 'MPL' AND SUBSTR(p.IRD, 1, 2)= 'PI' THEN 'PS'
WHEN p.PRODUCTO = 'MBK' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'ES'
WHEN p.PRODUCTO = 'MCB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MRG' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '95'
WHEN p.PRODUCTO = 'MDP' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'PS'
WHEN p.PRODUCTO = 'MRW' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MDB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MRL' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'TCO' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MPL' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'PS'
WHEN p.PRODUCTO = 'MWE' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'ES'
WHEN p.PRODUCTO = 'MNW' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'ES'
WHEN p.PRODUCTO = 'BPD' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MCW' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'PS'
WHEN p.PRODUCTO = 'MWB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'IP'
WHEN p.PRODUCTO = 'MRF' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MPB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MEB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MCO' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'TCB' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MLC' AND SUBSTR(p.IRD, 1, 2)= '75' THEN '61'
WHEN p.PRODUCTO = 'MCT' AND SUBSTR(p.IRD, 1, 2)= '75' THEN 'PS'

ELSE '??'
END AS CHAR(2)) "IRD A CAMBIAR"
--CAST(SUBSTR(p.IRD, 3) AS CHAR(10)) UBICACION
FROM IRD p
ORDER BY 5
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


INSERT INTO GXBDBPS.IPMFCTL
(IPMFCNAME ,
IPMFCINS ,
IPMFCSTS ,
IPMFCULTP ,
IPMFDWNL ,
IPMFUPDWN ,
IPMFCMEMB ,
BULKID ,
IPMFBRECQ ,
IPMFFECPRO,
IPMESTEJE ,
IPMUSUUPD)
VALUES
('T113035937', VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'PRC', NOW(), 'S', 'DWL', 'ICA19696', 'T113035937',
(SELECT CAST(COUNT(*) AS DEC(8, 0)) FROM GXBDBPS.IPMDTATE y WHERE y.IPMFNAME = 'T113035937' AND y.IPMDELN =2) , VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'S', 'MASTRUSR'),
('T113036038', VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'PRC', NOW(), 'S', 'DWL', 'ICA19696', 'T113036038',
(SELECT CAST(COUNT(*) AS DEC(8, 0)) FROM GXBDBPS.IPMDTATE y WHERE y.IPMFNAME = 'T113036038' AND y.IPMDELN =2) , VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'S', 'MASTRUSR')
WITH NC;


SELECT * FROM GXBDBPS.IPMFCTL WHERE IPMFCNAME LIKE 'T113112887%'
SELECT * FROM GXBDBPS.IPMDTA
SELECT * FROM GXBDBPS.IPMDTAT WHERE IPMFNAME IN ('T113112887') AND IPMMTI='1240'
SELECT * FROM GXBDBPS.IPMDTATE WHERE IPMFNAME IN ('T113112887') AND IPMMTI='1240'
SELECT * FROM GXBDBPS.IPMDTATEP WHERE IPMFNAME IN ('T113112887') AND IPMMTI='1240'

INSERT INTO GXBDBPS.IPMFCTL
(IPMFCNAME ,
 IPMFCINS  ,
 IPMFCSTS  ,
 IPMFCULTP ,
 IPMFDWNL  ,
 IPMFUPDWN ,
 IPMFCMEMB ,
 BULKID    ,
 IPMFBRECQ ,
 IPMFFECPRO,
 IPMESTEJE ,
 IPMUSUUPD)
VALUES
('T113036442', VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'PRC',  NOW(), 'S', 'DWL', 'ICA19696', 'T113036442',
 (SELECT CAST(COUNT(*) AS DEC(8, 0)) FROM GXBDBPS.IPMDTATE y WHERE y.IPMFNAME = 'T113036442' AND y.IPMDELN =2) , VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'S',   'MASTRUSR')
WITH NC;

SELECT * FROM GXBDBPS.IPMFCTL
SELECT * FROM GXBDBPS.ipmdtaep WHERE
IPMARN = '12306110359358264622509'        

SELECT * FROM GXBDBPS.ipmdtatep WHERE
IPMARN = '12306110359358264622509' 

SELECT * FROM GXBDBPS.GEMPRAF


INSERT INTO GXBDBPS.IPMFCTL
(IPMFCNAME ,
IPMFCINS ,
IPMFCSTS ,
IPMFCULTP ,
IPMFDWNL ,
IPMFUPDWN ,
IPMFCMEMB ,
BULKID ,
IPMFBRECQ ,
IPMFFECPRO,
IPMESTEJE ,
IPMUSUUPD)
VALUES
('T113100553', VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'PRC', NOW(), 'S', 'DWL', 'ICA19696', 'T113100553',
(SELECT CAST(COUNT(*) AS DEC(8, 0)) FROM GXBDBPS.IPMDTATE y WHERE y.IPMFNAME = 'T113100553' AND y.IPMDELN =2) , VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD'), 'S', 'MASTRUSR')

SELECT * FROM GXBDBPS.IPMFCTL WHERE IPMFCNAME LIKE 'T1130%'
SELECT * FROM GXBDBPS.IPMFCTL WHERE IPMFCNAME IN ('T113036545','T113036544')

SELECT * FROM GXBDBPS.IPMDTAT where  IPMMTI='1240' --IPMFNAME = 'R111103621' --IPMMSGREP = 'X'
SELECT * FROM GXBDBPS.IPMDTAT WHERE IPMARN IN ('12306111036034383985452')
SELECT * FROM GXBDBPS.IPMDTAE WHERE IPMARN IN ('12306110357355249804543')
SELECT * FROM GXBDBPS.IPMDTATE WHERE IPMDELN='2' AND IPMTDEV='5162921308576933' OR IPMDELN='4' AND IPMTDEV='000001061420'    
SELECT * FROM GXBDBPS.IPMDTAEP WHERE IPMARN IN ('12306110357355249804543','12306110358357259958069') AND IPMMSGSENT='O'
ORDER BY IPMARN, IPMFNAME


SELECT ViTranType FROM VISA.VISTRNDTA GROUP BY ViTranType
SELECT * FROM GXBDBPS.IPMDTAE WHERE ipmdeln = 2 AND IPMDEV='5428209999993264'

SELECT * FROM ARNALDOLIB.IPMDTAT;
SELECT * FROM ARNALDOLIB.IPMDTATE;
SELECT * FROM ARNALDOLIB.IPMDTATEP;

SELECT * FROM GXBDBPS.IPMDTAT;
SELECT * FROM GXBDBPS.IPMDTATE;
SELECT * FROM GXBDBPS.IPMDTATEP;

SELECT * FROM MASTERCARD.MASTRNDTA WHERE MCRRNBEPSA IN ('125187747070');
SELECT * FROM MASTERCARD.MASCTLDTA WHERE MCRRNBEPSA IN ('125187747070');

--***************************************************************************************************************************************************************************************--
select * from GXBDBPS.ipmdtae where ipmfname = 'R111104233' and ipmdeln = 40
[16:09] Perla Lopez
    SELECT * FROM gxbdbps.ipmdta WHERE IPMMSGSENT = 'R' AND IPMMTI='1240' AND IPMFNAME = 'R111125210'
 		SELECT * FROM gxbdbps.ipmdta WHERE   IPMMSGREP <> 'S' AND IPMARN=''
 		SELECT * FROM gxbdbps.ipmdtaT WHERE IPMMTI='1240' AND IPMARN IN ('12306111250247869840251','12306111250247870528325','12306111250249873359849','12306111250249873496203','12306111237236827937166')
	--DELETE FROM GXBDBPS.IPMDTA WHERE IPMFNAME='R111125208';
	--DELETE FROM GXBDBPS.IPMDTAE WHERE IPMFNAME='R111125208';
	--DELETE FROM GXBDBPS.IPMDTAEP WHERE IPMFNAME='R111125208';
SELECT * FROM ARNALDOLIB.IPMD


SELECT A.* FROM GXBDBPS.BULKDTA AS A          
        INNER JOIN GXBDBPS.IPMFMDTA AS B
        
        ON SUBSTRING(BULKID, 1, 4) =    
        B.IPMFMPRF WHERE B.IPMFACT = 'S' and substr(A.bulkid, 1, 4) = 'T113' AND BULKUSUPRO='U99ARNALDO'
       
SELECT count(*) FROM GXSWTDTA.BULKDTA;
SELECT count(*) FROM GXBDBPS.BULKDTA 

select * from gxbdbps.gcmsrdta where gcmsfnam like 'T1401090%'
select * from gxbdbps.IPMFCTL where IPMFCNAME like 'T1401125%'
SELECT * FROM GXBDBPS.BULKDTA WHERE BULKID LIKE '%T46407824123%'
SELECT * FROM GXBDBPS.MCT464FHDR
SELECT * FROM GXBDBPS.MCT464EREC WHERE T464FHRID='432'
SELECT * FROM GXBDBPS.MCT464FRDR WHERE T464FHRID='432'

SELECT * FROM GXBDBPS.IPMDTAT WHERE IPMARN = '55432861226200223215170';
SELECT * FROM GXBDBPS.IPMDTATE WHERE IPMARN = '55432861226200223215170';
SELECT * FROM GXBDBPS.IPMDTATEP WHERE IPMARN = '55432861226200223215170';

SELECT * FROM ARNALDOLIB.IPMDTATEP;
SELECT * FROM GXBDBPS.IPMDTAT WHERE IPMMSGREP='S'--IPMFNAME IN ('T113112682','T113112683') AND IPMMTI='1240'
SELECT * FROM GXBDBPS.IPMDTA where IPMARN = '55432861226200223215170';
SELECT * FROM GXBDBPS.IPMDTAE where IPMARN = '55432861226200223215170';
SELECT * FROM GXBDBPS.IPMDTAEp where IPMARN = '55432861226200223215170';
SELECT * FROM MASTERCARD.MASTRNDTA WHERE MCPANNMBR LIKE '%5476970000000065%' AND MCFECREAL BETWEEN '20210813' AND '20210815';
SELECT * FROM MASTERCARD.MASCTLDTA WHERE MC002 LIKE '%5476970000000065%' AND DATE(MCREVDATT) BETWEEN '2021-08-13' AND '2021-08-15';

SELECT * FROM GXBDBPS.TMOVIAF WHERE MTNUMTA LIKE '547697%' AND MVFEPRO='20210922'
SELECT * FROM GXBDBPS.TAUTPAF WHERE --MTNUMTA = '5476970000000065'












--Control de reenvíos del Dia.
SELECT
w.IPMFNAME "Archivo Rech",
w.IPMICA   "ICA" ,
w.IPMMTI   "MTI",
w.IPMARN   "ARN",
--w.IPMMSGREP,
CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 12) LIMIT 1),' ')
                    AS CHAR(6)) "Fecha Trx",
                    
               CAST(IFNULL( (SELECT INSERT (SUBSTR(u.IPMTDEV, 1, 16), 7, 6, '******')
                       FROM GXBDBPS.IPMDTATE u
                       WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                             (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 2)   LIMIT 1),' ')
                      AS CHAR(16)) "Tarjeta", -- INSERT("LNRTAR", 7, 6, '******'), 
                       
--              			 INSERT("LNRTAR", 7, 6, '******'),
	                  
									CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 37) LIMIT 1),' ')
                    AS CHAR(12)) "RRN",	  
                        
							 CAST(IFNULL(  (SELECT (SUBSTR(TRIM(u.IPMTDEV), 39, 2))
                       FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 48) LIMIT 1),' ')
                    AS CHAR(2)) "IRD",  
                                                  
	 					  CAST('REENVIOS' AS CHAR(15)) "Tipo Envío",
	 					  
							CAST(IFNULL(  (SELECT (SUBSTR(TRIM(u.IPMTDEV), 1, 3))
                       FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 63) LIMIT 1),' ')
                    AS CHAR(3)) "Producto",
                    
							CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 26) LIMIT 1),' ')
                      AS CHAR(6)) "MCC",
                      
							CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 38) LIMIT 1),' ')
                    AS CHAR(6))  "Cod.Aut.",
             CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 49) LIMIT 1),' ')
                    AS CHAR(3)) "Moneda",                    
             CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 4) LIMIT 1),' ')
                    AS CHAR(15)) "Importe",
             CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 123) LIMIT 1),' ')
                    AS CHAR(15)) "Archivo", 
						 CAST(IFNULL( (SELECT u.IPMTDEV
                        FROM GXBDBPS.IPMDTATE u
                        WHERE (u.IPMFNAME, u.IPMICA, u.IPMMTI, u.IPMARN, u.IPMICA, u.IPMDELN)=
                              (w.IPMFNAME, w.IPMICA, w.IPMMTI, w.IPMARN, w.IPMICA, 123) LIMIT 1),' ')
                    AS CHAR(15)) "Fec.Envío"
            FROM GXBDBPS.IPMDTAT  w
            WHERE w.IPMFNAME ='R111118391' AND
			      w.IPMMTI = 1240 AND
    	  		w.IPMICA = 19696
    	  		

SELECT * FROM MASTERCARD.MIPIPMLOG 
ORDER BY DRVLOGFECH DESC, DRVLOGHORA DESC

SELECT * FROM MASTERCARD.MASCTLDTA WHERE  MC002 LIKE '%5476970000000065%' AND MC043 LIKE '%AMZN%'--DATE (MCREVDATT) BETWEEN '2021-09-13' AND '2021-09-18' AND
SELECT * FROM MASTERCARD.MASTRNDTA WHERE MCPANNMBR LIKE '%5476970000000065%' AND MCFECREAL BETWEEN '20210814' AND '20210816';
