--Sentencias para Multiclearing

SELECT * FROM GXOPERA.TRXINST where insPGENTID = '16906';
DELETE GXOPERA.TRXINST where insPGENTID='16906';

SELECT * FROM GXOPERA.FLICOM WHERE LINRO ='16906';
DELETE GXOPERA.FLICOM WHERE LINRO='16906';

SELECT * FROM GXOPERA.FLICOM1 WHERE LINROINS ='16906';
DELETE GXOPERA.FLICOM1 WHERE LINROINS='16906';
---
SELECT * FROM GXOPERA.TRXINST where insPGENTID = '16907';
DELETE GXOPERA.TRXINST where insPGENTID='16907';

SELECT * FROM GXOPERA.FLICOM WHERE LINRO ='16907';
DELETE GXOPERA.FLICOM WHERE LINRO='16907';

SELECT * FROM GXOPERA.FLICOM1 WHERE LINROINS ='16907';
DELETE GXOPERA.FLICOM1 WHERE LINROINS='16907';
