SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX t GROUP BY AUXTBL,AUXEST ; 


SELECT * FROM GXTRJDTA.TDSSPr ;												


-------------------------- PCON003 ----------------

SELECT  * FROM   t GROUP BY AUXTBL,AUXEST ; 


SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX WHERE AUXTBL = 'TMTARAF' GROUP BY  AUXTBL,AUXEST ;	


SELECT T.*,a.*
FROM GXTRJDTA.TTCTRJ a
INNER JOIN GXTRJDTA.TDGAFI
ON TRJCODENT = ENTCODENT
AND TRJCODAFI = AFICODAFI
INNER JOIN GXTRJDTA.TCOAUX t 
ON TRJNROTRJ = AUXCLAV ;

-------------------------- PCON015 --------------------------------------


SELECT count(*) FROM GXTRJDTA.TCOAUX WHERE AUXTBL = 'TMCTAAF'

SELECT AUXTBL,AUXEST,MCNUMCT,MCEMISO,MCAFINI,MCBINES FROM GXTRJDTA.TCOAUX WHERE AUXTBL = 'TMCTAAF' GROUP BY  AUXTBL,AUXEST ;	
--===================================================================================
	SELECT COUNT(*)--SUBSTRING(AUXCLAV,1,12) ,AUXEST,MCNUMCT,MCEMISO,MCAFINI,MCBINES
	FROM GXTRJDTA.TCOAUX T  
	LEFT JOIN GXBDBPS.TMCTAAF A  ON MCNUMCT = AUXCLAV   --- TABLA DE CUENTA VIEJA 
	LEFT JOIN GXTRJDTA.TCOENC B  ON MCEMISO = B.EnCEntAnt --- RELACIONA ENTIDAD VIEJA CON NEUVA 
	LEFT JOIN  GXTRJDTA.TCOEAC c ON  A.MCEMISO =  C.EACEntAnt AND  A.MCBINES = c.EACBINAnt   AND A.MCAFINI = c.EACAFIANT 
	WHERE AUXTBL = 'TMCTAAF' AND AUXEST = 'N' AND  NOT MCNUMCT IS NULL AND c.EACAFIANT IS null;


	SELECT  FROM GXBDBPS.TMCTAAF WHERE  MCNUMCT =  '601039999999' 
	
	SELECT EACEntAnt,EACBINAnt,EACAFIANT FROM GXTRJDTA.TCOEAC c WHERE  
	C.EACEntAnt IN ('999','601','318','314','313','309','002','178','156') AND 
	c.EACAFIANT IN ('001','002','010','009','007','006','005') AND c.EACBINAnt ='627431'   ; 


SELECT CTAIDCTA,AUXCLAV,CTACODENT, ENTCODENT,CTACODAFI ,AFICODAFI
FROM GXTRJDTA.TTCCTA 
INNER JOIN GXTRJDTA.TDGAFI ON  CTACODENT = ENTCODENT AND CTACODAFI = AFICODAFI
INNER JOIN  GXTRJDTA.TCOAUX T ON  SUBSTRING(CTAIDCTA,0,12) = AUXCLAV   AND  T.AUXEST = 'P';
---================================================================================

-------------------------- PCON017 --------------------------------------
 SELECT count(*) FROM GXTRJDTA.TCOAUX 
 WHERE  AUXTBL IN ('TDCLIENTE' ,'TDCLIENTED' ,'GCLIEAF' , 'GDIREAF')
 
 
 
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TDCLIENTE' ,'TDCLIENTED' ,'GCLIEAF' , 'GDIREAF')  GROUP BY  AUXTBL,AUXEST ;

SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TDCLIENTED')  GROUP BY  AUXTBL,AUXEST ;	

SELECT AUXTBL,AUXEST,AUXCLAV, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TDCLIENTE')  GROUP BY  AUXTBL,AUXEST, AUXCLAV ;	

--=========================================TDCLIENTE=============================================
 SELECT   COUNT(*)--   SUBSTRING(AUXCLAV,1,4) , SUBSTRING(AUXCLAV,2,3), SUBSTRING(AUXCLAV,5,3), SUBSTRING(AUXCLAV,8,15),AUXEST ,C.* 
 FROM GXTRJDTA.TCOAUX 
 LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,2,3)
 LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
 --LEFT JOIN  GXTRJDTA.TDGPER C  ON   SUBSTRING(AUXCLAV,5,3) = TDoIdTpDoc AND  PerNroDoc = SUBSTRING(AUXCLAV,8,15) 
 WHERE  AUXTBL IN ('TDCLIENTE')  and AUXEST  = 'N'  AND PaSIdParSi IS NULL ;
 
--======================================= TDCLIENTED===============================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TDCLIENTED')  GROUP BY  AUXTBL,AUXEST ;


SELECT  count(*) -- SUBSTRING(AUXCLAV,1,4) , SUBSTRING(AUXCLAV,2,3), SUBSTRING(AUXCLAV,5,3), SUBSTRING(AUXCLAV,8,15), SUBSTRING(AUXCLAV,23,2) , AUXEST ,c.* 
 FROM GXTRJDTA.TCOAUX 
 LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,2,3)
 LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
 LEFT JOIN  GXTRJDTA.TDGPER C  ON   SUBSTRING(AUXCLAV,5,3) = TDoIdTpDoc AND  PerNroDoc = SUBSTRING(AUXCLAV,8,15) 
 WHERE  AUXTBL IN ('TDCLIENTED')  and AUXEST  = 'N'  ;
 

--------------------------------------------------------------------------------------------------

SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('GCLIEAF')  GROUP BY  AUXTBL,AUXEST ;

SELECT count (*) --SUBSTRING(AUXCLAV,1,3) , SUBSTRING(AUXCLAV,4,1), SUBSTRING(AUXCLAV,5,15), AUXEST ,C.*
FROM GXTRJDTA.TCOAUX 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,1,3)  
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
LEFT JOIN GXBDBPS.GCLIEAF C  
ON  ENEMISO = SUBSTRING(AUXCLAV,1,3) AND CETIPOD = SUBSTRING(AUXCLAV,4,1)  AND  CENUMDO = SUBSTRING(AUXCLAV,5,15)  
WHERE  AUXTBL IN ('GCLIEAF')  and AUXEST  = 'N'    ;


----------------------------------------------------------------------------------------------------------------------------

SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('GDIREAF')     GROUP BY  AUXTBL,AUXEST ;

SELECT count(*)--SUBSTRING(AUXCLAV,1,3) , SUBSTRING(AUXCLAV,4,1), SUBSTRING(AUXCLAV,5,15), AUXEST ,a.*
FROM GXTRJDTA.TCOAUX 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,1,3)   AND EnCEntAnt IS null
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  AND  PaSIdParSi IS NULL 
LEFT JOIN GXBDBPS.GCLIEAF C  ON  ENEMISO = SUBSTRING(AUXCLAV,1,3) AND CETIPOD = SUBSTRING(AUXCLAV,4,1)  AND  CENUMDO = SUBSTRING(AUXCLAV,5,15)  AND CETIPOD IS NULL
WHERE  AUXTBL IN ('GDIREAF')  and AUXEST  = 'N'    ;

SELECT  COUNT(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('GDIREAF') and AUXEST  = 'N'   ;


--=============================================PCON014=====================================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TAFINAF')     GROUP BY  AUXTBL,AUXEST ;



SELECT Count(*)--SUBSTRING(AUXCLAV,1,3)/*enemiso*/ , SUBSTRING(AUXCLAV,4,6)/*BIBINES*/, SUBSTRING(AUXCLAV,10,3)/*AFAFINI*/, AUXEST, c.*
FROM GXTRJDTA.TCOAUX 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,1,3)   AND EnCEntAnt IS null
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  AND  PaSIdParSi IS NULL 
LEFT JOIN GXBDBPS.TAFINAF C  
ON C.ENEMISO  = SUBSTRING(AUXCLAV,1,3) AND C.AFAFINI =  SUBSTRING(AUXCLAV,10,3) AND C.BIBINES  = SUBSTRING(AUXCLAV,4,6)	
WHERE  AUXTBL IN ('TAFINAF')  and AUXEST  = 'N'    ;

--=============================================PCON013=====================================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TDEMIS')     GROUP BY  AUXTBL,AUXEST ;




SELECT cOUNT (*)--SUBSTRING(AUXCLAV,1,4)/*enemiso*/ , SUBSTRING(AUXCLAV,2,3) ,SUBSTRING(AUXCLAV,5,6),SUBSTRING(AUXCLAV,11,1),SUBSTRING(AUXCLAV,12,1),SUBSTRING(AUXCLAV,13,12)/*BIBINES*//*AFAFINI*/, AUXEST,C.*
FROM GXTRJDTA.TCOAUX 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,2,3)   
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
LEFT JOIN GXBDBPS.TDEMIS C
ON C.TDBINENTID  = SUBSTRING(AUXCLAV,2,3) 	 AND  TDBINENTID IS NULL
WHERE  AUXTBL IN ('TDEMIS') and AUXEST  = 'N'     ;

--=============================================PCON036=====================================

SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TCCCTAF')     GROUP BY  AUXTBL,AUXEST ;


SELECT COUNT(*)--SUBSTRING(AUXCLAV,1,12),SUBSTRING(AUXCLAV,2,3),SUBSTRING(AUXCLAV,1,12),SUBSTRING(AUXCLAV,13,3),SUBSTRING(AUXCLAV,12,1),SUBSTRING(AUXCLAV,13,3)/*BIBINES*//*AFAFINI*/,auxACCI, AUXEST,C.*
FROM GXTRJDTA.TCOAUX 
LEFT JOIN GXBDBPS.TCCCTAF C
ON C.KCNUMCT   = SUBSTRING(AUXCLAV,1,12) 	 AND  KCCODIG  = SUBSTRING(AUXCLAV,13,3)
WHERE  AUXTBL IN ('TCCCTAF')  and AUXEST  = 'N'     ;



SELECT * FROM GXBDBPS.TCCCTAF;
--======================================PCON031====================================================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TCCONAF')     GROUP BY  AUXTBL,AUXEST ;


SELECT AUXCLAV ,ENCENTACT,AUXFEHO,COUNT(*)
FROM GXTRJDTA.TCOAUX T 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,4,3)    
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
LEFT JOIN GXBDBPS.TAFINAF  C ON  c.ENEMISO  = SUBSTRING(AUXCLAV,4,3)   AND C.BIBINES  =  SUBSTRING(AUXCLAV,7,6) AND C.AFAFINI  = SUBSTRING(AUXCLAV,13,3)
 LEFT JOIN GXTRJDTA.TCoEAC  D  oN A.EnCEntAct = D.EACEntAct AND  D.EACEntAnt = C.ENEMISO AND C.AFAFINI  = EACAfiAnt
LEFT JOIN GXTRJDTA.TDGADF  E  ON  e.EntCodEnt  =  A.EnCEntAct AND e.AfiCodAfi = d.EACAfiAnt
WHERE  AUXTBL IN ('TCCONAF') and AUXEST  = 'N' AND  NOT  EnCEntAnt IS NULL  AND  NOT  PaSIdParSi IS NULL  AND NOT  D.EACEntAct  IS NULL AND  e.EntCodEnt IS NULL 
GROUP BY  AUXCLAV ,ENCENTACT  ,AUXFEHO 
--LEFT JOIN GXBDBPS.TCCCTAF C
--ON C.KCNUMCT   = SUBSTRING(AUXCLAV,1,12) 	 AND  KCCODIG  = SUBSTRING(AUXCLAV,13,3)

--==================================================PCON036========================================================

SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TMO1MAF')     GROUP BY  AUXTBL,AUXEST ;



SELECT*
FROM GXTRJDTA.TCOAUX T 
--LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,4,3)    
--LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
--LEFT JOIN GXBDBPS.TAFINAF  C ON  c.ENEMISO  = SUBSTRING(AUXCLAV,4,3)   AND C.BIBINES  =  SUBSTRING(AUXCLAV,7,6) AND C.AFAFINI  = SUBSTRING(AUXCLAV,13,3)
 --LEFT JOIN GXTRJDTA.TCoEAC  D  oN A.EnCEntAct = D.EACEntAct AND  D.EACEntAnt = C.ENEMISO AND C.AFAFINI  = EACAfiAnt
--LEFT JOIN GXTRJDTA.TDGADF  E  ON  e.EntCodEnt  =  A.EnCEntAct AND e.AfiCodAfi = d.EACAfiAnt
WHERE  AUXTBL IN ('TMO1MAF') and AUXEST  = 'P' 

--==========================================================pcon040==============================================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TCUENOCOB')     GROUP BY  AUXTBL,AUXEST ;


--==========================================================pcon040==============================================
SELECT AUXTBL,AUXEST, count(*) FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TMANENCTA')     GROUP BY  AUXTBL,AUXEST ;

SELECT count(*)--SUBSTRING(AUXCLAV,1,3), SUBSTRING(AUXCLAV,4,3),C.*  
FROM GXTRJDTA.TCOAUX T 
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = SUBSTRING(AUXCLAV,1,3)    
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
LEFT JOIN  GXBDBPS.TMANENCTA c ON MCEENE = SUBSTRING(AUXCLAV,1,3)  AND  MECECO = SUBSTRING(AUXCLAV,4,3)
WHERE  AUXTBL IN ('TMANENCTA') and AUXEST  = 'N' AND  MCEENE IS NULL;
 
SELECT * FROM GXTRJDTA.TCOAUX t WHERE  AUXTBL IN ('TMANENCTA') AND AUXCLAV IN ('021005','021008','021012','021019','021024','020005','020017','020022','020023','020024','020025','020026','020027','020028','020029','020030','020031','020032','020033','020034','020035','020036','020037','020038','020039','020040','020041','020042','020043','020044','020045','020046','020047','020048','020049','020050','020051','020052','020053');

------=================================PCON046=======================================
SELECT * FROM GXTRJDTA.TCOAUX 
WHERE AUXTBL IN ('TCODEAF') ;

SELECT *
FROM GXTRJDTA.TCOAUX T 
LEFT JOIN  GXBDBPS.TCODEAF	 c ON C.MTNUMTA = SUBSTRING(AUXCLAV,2,16)
LEFT JOIN  GXBDBPS.TMTARAF	 D ON D.MTNUMTA = SUBSTRING(AUXCLAV,2,16)
LEFT JOIN  GXTRJDTA.TCoEnC A ON EnCEntAnt = D.ENEMISO   
LEFT JOIN  GXTRJDTA.TDSDPS B  ON  PaSIdParSi = 'ACTUALIZACIONKBTRJ' AND A.ENCENTACT  = DPSSecue  
WHERE  AUXTBL IN ('TCODEAF') AND NOT  D.MTNUMTA  IS NULL;
 
SELECT * FROM GXBDBPS.TCODEAF  ;


SELECT * FROM GXTRJDTA. 	TDSPRC t  WHERE MODIDMODUL = 'CO';

UPDATE   GXTRJDTA.TDSPRC t   SET PRCESTADO = 'I'  WHERE MODIDMODUL = 'CO' AND  PRCIDPROCE <> 'PCON046';

