INSERT INTO GXSEGDTA.TSGARU (SGROLCOD,SGSISCOD,SGUSRCOD,SGARUEXP,SGARUUSMO,SGARUFCHMO,SGARUENTRJ) VALUES (
278,33,2925,'N','          ', CURRENT_TIMESTAMP,' '); --LAURA SANCHEZ

INSERT INTO GXSEGDTA.TSGARU (SGROLCOD,SGSISCOD,SGUSRCOD,SGARUEXP,SGARUUSMO,SGARUFCHMO,SGARUENTRJ) VALUES (
278,33,2929,'N','          ', CURRENT_TIMESTAMP,' '); --JOSE CHAMORRO

select * from GXSWTDTA.TSWTPSW 

SELECT * FROM GXSEGDTA.TSGSIS t WHERE SGSISCOD IN (21, 1, 2, 33)

-- Tabla sistemas
SELECT * FROM GXSEGDTA.TSGSIS

 

--Tabla Rol
SELECT * FROM GXSEGDTA.TSGROL

 

-- Tabla Usuario
SELECT * FROM GXSEGDTA.TSGUSR

JOSE 2011
HERNAN 1942

-- Relación Usuario/Rol
SELECT * FROM gxsegdta.TSGARU
where SGUSRCOD in ('2011', '2942')

 

--Relación ROl/FUnciones u Objetos gx
SELECT * FROM GXSEGDTA.TSGROLDT 

 

-- Tabla FUnciones u objetos gx
SELECT * FROM GXSEGDTA.TSGFUN where SGFUNCOD='2629'

-- Tabla FUnciones u objetos gx
SELECT * FROM GXSEGDTA.TSGFUN where SGFUNOBJ like 'TDGTSA%'

-- Tabla FUnciones u objetos gx
delete GXSEGDTA.TSGFUN where SGFUNOBJ='WCL001'

