SELECT * FROM VIRGILILIB.OPMMARC; 
SELECT COENADM, COCOMER                                              
  FROM GXBDBPS.COMAEAF INNER JOIN GXOPERA.OPENTID ON COENADM = '087' 
 WHERE COCOMER = '9099439'
-- SUBSTR(COCOMER, 1, 2) = '45' 
 AND COENADM <> '999' AND COSTAT  = '0'
 GROUP BY COENADM, COCOMER    
 ORDER BY COENADM                       


Select ENEADM, 'ADM', LCODBC, LBCOCR, LIDCOM, LBINPR,               
        SUBSTR(LCODTR, 1, 2), ENEPRO, LENEMI, count(*) CANTIDAD, SUM(LIMPGS) IMPORTE,LERRNB,AUTRRNBEP,AUTTIPTAR
  from LIBDEBITO.DRCONBEP                                            
inner join GXBDBPS.TSWAUT ON LERRNB = AUTRRNBEP                     
 where lfectr = '20210524' and lcodbc = 'DIN' and LBCOCR = '520'     
   and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00'         
   and lesttr = 'A' and substr(lcodtr, 1, 2) = '01'                  
   and ENEADM = '002'                                             
   and LENEMI <> ENEADM --AND AUTTIPTAR = 'C'                          
 GROUP BY ENEADM, LCODBC, LBCOCR, LIDCOM, LBINPR, SUBSTR(LCODTR, 1,2),
       ENEPRO, LENEMI,LERRNB,AUTRRNBEP,AUTTIPTAR--585
       
Select * From gxopera.opentid;
Select ENEADM, 'PRO', LCODBC, LBCOCR, LIDCOM, LBINPR,               
        SUBSTR(LCODTR, 1, 2), ENEPRO, LENEMI, count(*) CANTIDAD, SUM(LIMPGS) IMPORTE,LERRNB,AUTRRNBEP,AUTTIPTAR
  from LIBDEBITO.DRCONBEP                                            
 inner join GXBDBPS.TSWAUT ON LERRNB = AUTRRNBEP                     
 where lfectr = '20210202' and lcodbc = 'DEB' and LBCOCR = '520'     
   and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00'         
   and lesttr = 'A' and substr(lcodtr, 1, 2) = '01'                  
   and ENEPRO = '087'                                             
   and LENEMI <> ENEPRO AND AUTTIPTAR = 'D'                    
 GROUP BY ENEADM, LCODBC, LBCOCR, LIDCOM, LBINPR, SUBSTR(LCODTR, 1,2),
       ENEPRO, LENEMI,LERRNB,AUTRRNBEP,AUTTIPTAR
       
--****************************************************************************
Select ENEADM, 'ADM', LCODBC, LBCOCR, LIDCOM, LBINPR,               
        SUBSTR(LCODTR, 1, 2), ENEPRO, LENEMI, count(*) CANTIDAD, SUM(LIMPGS) IMPORTE,LERRNB,AUTRRNBEP,AUTTIPTAR
  from LIBDEBITO.DRCONBEP                                            
 inner join GXBDBPS.TSWAUT ON LERRNB = AUTRRNBEP                     
 where lfectr = '20210201' and lcodbc = 'MST' and LBCOCR = '530'     
   and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00'         
   and lesttr = 'A' and substr(lcodtr, 1, 2) = '01'                  
   and ENEADM = '087'                                             
   and LENEMI <> ENEADM AND AUTTIPTAR = 'D'  
    AND LIDCOM = 9099439 AND LBINPR = '628095'                         
 GROUP BY ENEADM, LCODBC, LBCOCR, LIDCOM, LBINPR, SUBSTR(LCODTR, 1,2),
       ENEPRO, LENEMI,LERRNB,AUTRRNBEP,AUTTIPTAR
       
select * from LIBDEBITO.DRCONBEP
where lfectr = '20210201'
AND LIDCOM = 9099439 AND LBINPR = '628095';

--******************************************** SQL DE PRODUCCION A DESARROLLO DESPUES DE LA MODIFICACION
-- DETALLE POR BIN Y COMERCIO
select A.CAFECHA,A.CACODAD,A.CACOMER,A.CAPROCE,A.CAENEMI,A.CATARJE,A.CAMARCA,SUM(A.CACANAD) CANT_PRODUCCION,
B.CAFECHA,B.CACODAD,B.CACOMER,B.CAPROCE,B.CAENEMI,B.CATARJE,B.CAMARCA,SUM(B.CACANAD) CANT_PRUEBADESA
FROM VIRGILILIB.OPMCATM A,GXOPERA.OPMCATM B
WHERE --A.CAFECHA BETWEEN '20210201' AND '20210201' AND 
A.CAFECHA = B.CAFECHA
AND A.CACOMER= B.CACOMER
AND A.CAPROCE= B.CAPROCE
AND A.CAENEMI= B.CAENEMI
AND A.CATARJE= B.CATARJE
AND A.CAMARCA= B.CAMARCA
GROUP BY A.CAFECHA,A.CACODAD,A.CACOMER,A.CAPROCE,A.CAENEMI,A.CATARJE,A.CAMARCA,
B.CAFECHA,B.CACODAD,B.CACOMER,B.CAPROCE,B.CAENEMI,B.CATARJE,B.CAMARCA
ORDER BY A.CAFECHA,A.CACODAD,A.CACOMER,A.CAPROCE,A.CAENEMI,A.CATARJE,A.CAMARCA,
B.CAFECHA,B.CACODAD,B.CACOMER,B.CAPROCE,B.CAENEMI,B.CATARJE,B.CAMARCA;

-- POR ENTIDAD ADM, MARCA,PROCE, EMISOR, 

SELECT A.CACODAD,A.CAMARCA,A.CAPROCE,A.CAENEMI,SUM(A.CACANAD) AS CANTADM_PRODUC,
B.CACODAD,B.CAMARCA,B.CAPROCE,B.CAENEMI,SUM(B.CACANAD) AS CANTADM_PRUEBA
from VIRGILILIB.OPMCATM A,GXOPERA.OPMCATM B
WHERE --A.CAFECHA = '20210201' AND 
A.CAFECHA = B.CAFECHA
AND A.CACODAD = B.CACODAD
AND A.CAMARCA = B.CAMARCA 
AND A.CAPROCE = B.CAPROCE
GROUP BY A.CACODAD,A.CAMARCA,A.CAPROCE,A.CAENEMI,
B.CACODAD,B.CAMARCA,B.CAPROCE,B.CAENEMI
ORDER BY A.CACODAD,A.CAMARCA,A.CAPROCE,A.CAENEMI,
B.CACODAD,B.CAMARCA,B.CAPROCE,B.CAENEMI;

--***************************** POR ADM, MARCA, PROCESADORA
SELECT A.CACODAD,A.CAMARCA,A.CAPROCE,SUM(A.CACANAD) AS CANTADM_PRODUC,
B.CACODAD,B.CAMARCA,B.CAPROCE,SUM(B.CACANAD) AS CANTADM_PRUEBA
from VIRGILILIB.OPMCATM A, gxopera.OPMCATM B
WHERE A.CAFECHA BETWEEN '20210201' AND '20210201'
AND A.CAFECHA = B.CAFECHA
AND A.CACODAD = B.CACODAD
AND A.CAMARCA = B.CAMARCA 
AND A.CAPROCE = B.CAPROCE
GROUP BY A.CACODAD,A.CAMARCA,A.CAPROCE,
B.CACODAD,B.CAMARCA,B.CAPROCE
ORDER BY A.CACODAD,A.CAMARCA,A.CAPROCE,
B.CACODAD,B.CAMARCA,B.CAPROCE;

--################################################### COMPARACION DE PRUEBA VS PRODUCCION 
SELECT A.CACODAD,A.CAMARCA,A.CAPROCE,SUM(A.CACANAD) AS CANTADM_PRODUC
from VIRGILILIB.OPMCATM A
WHERE A.CAFECHA BETWEEN '20210517' AND '20210517'
GROUP BY A.CACODAD,A.CAMARCA,A.CAPROCE
ORDER BY A.CACODAD,A.CAMARCA,A.CAPROCE;

SELECT A.CACODAD,A.CAMARCA,A.CAPROCE,SUM(A.CACANAD) AS CANTADM_PRUEBA
from GXOPERA.OPMCATM A
WHERE A.CAFECHA BETWEEN '20210524' AND '20210524'
GROUP BY A.CACODAD,A.CAMARCA,A.CAPROCE
ORDER BY A.CACODAD,A.CAMARCA,A.CAPROCE;
--##############################################################################################
SELECT * FROM LIBDEBITO.TBINPROC;--430
SELECT * FROM VIRGILILIB.TBINPROC;--477

SELECT * FROM GXOPERA.OPMMARC;--37
SELECT * FROM VIRGILILIB.OPMMARC;--37

SELECT * FROM GXOPERA.OPMTARI where TAENADM in ('117','146');
SELECT * FROM VIRGILILIB.OPMTARI;

SELECT CAFECHA,COUNT(*) CANTIDAD FROM GXOPERA.OPMCATM
where CAFECHA = '20210201'
GROUP BY CAFECHA
ORDER BY CAFECHA;
--COMAEAF 
--CCCTCTA 
--CCCCCTE 
CCASIEN 
TAT7PAG 
--OPMMARC 
--OPMTARI 
--OPMCATM 

SELECT ASFECH,COUNT(*) FROM CONTABILID.CCASIEN --WHERE --ASFECH = 210201
GROUP BY ASFECH;
STRJRNPF FILE(CONTABILID/TAT7PAG) JRN(@JOURNAL/QSQJRN)
SELECT * FROM CONTABILID.TAT7PAG WHERE T7AAMM = 2102;
SELECT * FROM CONTABILID.TAT7PAGZ WHERE T7AAMM = 2102;
SELECT * FROM LIBCLEA.TSWAUT WHERE AUTTRXFCHF = '20210201'
SELECT AUTTRXFCHF,COUNT(*) FROM LIBCLEA.TSWAUT
WHERE auttrxfchf = '20210201' 
GROUP BY AUTTRXFCHF;-- 179.846

SELECT SUBSTR(AUTTRXFCHF,1,6),COUNT(*) FROM GXBDBPS.TSWAUT
WHERE SUBSTR(AUTTRXFCHF,1,6) = '202105' 
GROUP BY SUBSTR(AUTTRXFCHF,1,6);--2.802.539

SELECT substr(AUTTRXFCHF,1,6),COUNT(*) FROM yapi.TSWAUT
WHERE substr(AUTTRXFCHF,1,6) = '202105' 
GROUP BY substr(AUTTRXFCHF,1,6);--179.846

SELECT AUTTRXFCHF,COUNT(*) FROM virgililib.TSWAUTkp
WHERE substr(AUTTRXFCHF,1,6) = '202105' 
GROUP BY AUTTRXFCHF;--179.846

SELECT AUTRRNBEP FROM VIRGILILIB.DRCONBEKP
WHERE AUTTRXFCHF = '20210501' 
GROUP BY AUTTRXFCHF;--179.846

SELECT * FROM GXBDBPS.TSWAUT where 
AUTRRNBEP in (SELECT AUTRRNBEP FROM VIRGILILIB.DRCONBEKP)

select SUBSTR(lfectr,1,6),count(*) from virgililib.drconbep
where SUBSTR(lfectr,1,6) = '202105'
group by SUBSTR(lfectr,1,6) ;--123.441

select lfectr,count(*) from libdebito.drconbep
where lfectr = '20210202'
group by lfectr ;--237


SELECT CAFECHA,COUNT(*) CANTIDAD FROM GXOPERA.OPMCATM
where CAFECHA = '20210203'
GROUP BY CAFECHA
ORDER BY CAFECHA;

SELECT CAFECHA,COUNT(*) CANTIDAD FROM virgililib.OPMCATM
where substr(CAFECHA,1,6) = '202105'
GROUP BY CAFECHA
ORDER BY CAFECHA;


select  * FROM GXOPERA.OPMCATM
where CAFECHA > '20210524'
--GROUP BY CAFECHA
ORDER BY CAFECHA;

-- PRUEBA CON TIPOS DEB A CLA.. DEL MES DE MAYO
select LCODBC,COUNT(*) from libdebito.drconbep
where SUBSTR(lfectr,1,6) = '202105'
group by LCODBC;--237--2.802.915

select /*LCODBC,*/COUNT(*) from LIBDEBITO.drconbep
where SUBSTR(lfectr,1,6) = '202105'
group by LCODBC;--237--2.802.915

SELECT * FROM VIRGILILIB.DRCON180
select /*LCODBC,*/COUNT(*) from VIRGILILIB.DRCON180
where SUBSTR(Alfectr,1,6) = '202105'
group by LCODBC;--237--2.802.913

select lfectr,count(*) from libdebito.drconbep
where lfectr = '20210202'
group by lfectr ;--237


UPDATE libdebito.drconbep 
SET LCODBC = 'CLA'
where SUBSTR(lfectr,1,6) = '202105'
AND LCODBC = 'DEB';--58.146

SELECT * FROM GXOPERA.OPMMARC WHERE MACOBC = 'CLA';
UPDATE GXOPERA.OPMMARC
   SET MACOBC = 'DEB'
WHERE MACOBC = 'CLA';
/*UPDATE GXOPERA.OPMMARC
   SET MACOBC = 'DEB'
WHERE MATIPO = 'CLA'
AND   MACOBC = 'DEB'
AND   MACOCR = '520'
AND   MADESL = 'DINELCO DEBITO      '
AND   MADESC = 'DIN.DEBITO'
AND   MACODI = '  ';*/

SELECT * FROM GXOPERA.OPMTARI WHERE TAMARCA = 'DEB';
UPDATE GXOPERA.OPMTARI
   SET TAMARCA = 'DEB'
WHERE TAMARCA = 'CLA';--36
--SELECT COUNT(*) FROM Virgililib.OPMCATM WHERE CAMARCA = 'DEB'

UPDATE Virgililib.OPMCATM
   SET CAMARCA = 'DEB'
WHERE SUBSTR(CAFECHA,1,6) = '202105'
AND  CAMARCA = 'CLA';-- 9770


--DELETE FROM GXOPERA.OPMCATM WHERE substr(CAFECHA,1,6) = '202105'
SELECT * FROM CCORREA.TDSSDP WHERE SPRIDSEG =7287850;


delete from GXOPERA.OPMCATM where  substr(CAFECHA,1,6) = '202105';

delete from GXOPERA.OPMCATM A
WHERE A.CAFECHA BETWEEN '20210501' AND '20210531'
GROUP BY A.CACODAD,A.CAMARCA,A.CAPROCE
ORDER BY A.CACODAD,A.CAMARCA,A.CAPROCE;


select * from gxswtdta.NUT009 where MTID = 'VSA';
select * from gxbdbps.NUT009 where MTID = 'VSA';


select ENEADM, 'ADM', LCODBC, LBCOCR, LIDCOM, LBINPR,               
        SUBSTR(LCODTR, 1, 2), ENEPRO, LENEMI, LIMPGS IMPORTE,LERRNB
         from libdebito.drconbep where LBINPR = '703002' and 
         substr(lfectr,1,6) = '202105'
         and ENEPRO <> lenemi
         and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00'         
   and lesttr = 'A' and substr(lcodtr, 1, 2) = '01';
   
select * from 
