-- por COMERCIO, BIN Y OTROS EN drconbep MST
Select LBINPR,LIDCOM,lcodbc,LBCOCR,LBCOCR,LENEMI,SUM(LIMPGS) IMPORTE, COUNT(*)
from virgililib.drconbep
where lfectr between '20210201' and '20210201' and lcodbc IN ('MST') and LBCOCR = '530' and ENEADM = '087'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00' and LENEMI <> ENEPRO
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01' --and ENEADM = '002'
GROUP BY LBINPR,LIDCOM,lcodbc,LBCOCR,LBCOCR,LENEMI
ORDER BY LBINPR,LIDCOM,lcodbc,LBCOCR,LBCOCR,LENEMI;

-- por COMERCIO, BIN Y OTROS EN opmcatm
SELECT CATARJE AS BIN,CACOMER,CAENEMI,CAPROCE,CACODAD, SUM(CACANAD) AS CANTIDAD
from GXOPERA.OPMCATM
WHERE CAFECHA = '20210201' 
AND CACODAD = '074'
AND CAMARCA = 'VSA' 
AND CAPROCE IN ('540','015','020')
AND CAENEMI <> '074'
group by  CATARJE,CACOMER,CAENEMI,CAPROCE,CACODAD
ORDER BY CATARJE,CACOMER,CAENEMI,CAPROCE,CACODAD;

--***************************************PARA VISA
-- por COMERCIO, BIN Y OTROS EN drconbep MST
Select LBINPR,LIDCOM/*,lcodbc,LBCOCR,LBCOCR,LENEMI*/,SUM(LIMPGS) IMPORTE, COUNT(*) CANTIDAD
from virgililib.drconbep
where lfectr between '20210201' and '20210201' 
and lcodbc = 'MST' and LBCOCR IN ('530')--('540','015','020') 
and ENEPRO = '581'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' 
and lcretr = '00' and LENEMI <> ENEPRO
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01' --and ENEADM = '002'
GROUP BY LBINPR,LIDCOM/*,lcodbc,LBCOCR,LBCOCR,LENEMI*/
ORDER BY LBINPR,LIDCOM/*,lcodbc,LBCOCR,LBCOCR,LENEMI*/;

-- por COMERCIO, BIN Y OTROS EN opmcatm
SELECT CATARJE AS BIN,CACOMER/*,CAENEMI,CAPROCE,CACODAD*/, SUM(CACANAD) AS CANTIDAD
from GXOPERA.OPMCATM
WHERE CAFECHA = '20210201' 
AND CACODPR = '581'
AND CAMARCA = 'MST'--'VSA'
AND CAPROCE IN ('530')--('540','015','020')
AND CAENEMI <> '581'
group by  CATARJE,CACOMER/*,CAENEMI,CAPROCE,CACODAD*/
ORDER BY CATARJE,CACOMER/*,CAENEMI,CAPROCE,CACODAD*/;


--------------------- entidad y comercio
--6280950000524506
select * from gxtrjdta.tdgbin where BINNROBIN like '628095%';
SELECT AUTTIPTAR FROM GXBDBPS.TSWAUT WHERE AUTRRNBEP = '103237816016   ';

SELECT *
--LENEMI,LBCOCR,ENEADM,ENEPRO,LBINPR,LIDCOM,LCODPR,LERRNB
from libdebito.drconbep
where lfectr between '20210201' and '20210201' and lcodbc IN ('MST')--,'VSA') 
and LBCOCR IN ('530')--,'015')--= '530'
 and ENEADM = '087'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' 
and lcretr = '00' and LENEMI <> ENEPRO and lesttr = 'A' 
and substr(lcodtr, 1, 2) = '01'  
 AND LIDCOM IN (9099439)
AND LBINPR IN (628095)
ORDER BY LENEMI,LBCOCR,ENEADM,ENEPRO,LBINPR,LIDCOM,LCODPR,LERRNB;


--******************************* POR COMERCIO
SELECT * 
from GXOPERA.OPMCATM
WHERE CAFECHA = '20210201' 
AND CACODPR = '087'
AND CAMARCA = 'MST'--'MST' 
AND CAPROCE IN ('530')--,'015')--'530' 
AND CAENEMI <> '087'
AND CACOMER = '9099439' AND CATARJE = '628095'
ORDER BY CATARJE,CACOMER/*,CAENEMI,CAPROCE,CACODAD*/;

-------------------------VSA--------------------------- 
-- por COMERCIO, BIN Y OTROS EN drconbep
-- ADM
Select LBINPR,LIDCOM,'ADM',/*lcodbc,LBCOCR,LBCOCR,LENEMI,*/SUM(LIMPGS) IMPORTE, COUNT(*)
from virgililib.drconbep
where lfectr between '20210201' and '20210201' 
--and lcodbc IN ('MST') and LBCOCR = '530' 
and lcodbc = 'VSA' and LBCOCR IN ('500')--,'510')
and ENEADM = '002'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00' and LENEMI <> ENEADM
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01' AND SUBSTR(LIDTRA,1,1) = 'T'
GROUP BY LBINPR,LIDCOM--,lcodbc,LBCOCR,LBCOCR,LENEMI
ORDER BY LBINPR,LIDCOM;--,lcodbc,LBCOCR,LBCOCR,LENEMI;
-------------- PRO
Select LBINPR,LIDCOM,'PRO',/*lcodbc,LBCOCR,LBCOCR,LENEMI,*/SUM(LIMPGS) IMPORTE, COUNT(*)
from virgililib.drconbep
where lfectr between '20210201' and '20210201' 
--and lcodbc IN ('MST') and LBCOCR = '530' 
and lcodbc = 'VSA' and LBCOCR IN ('550','510')
and ENEPRO = '002'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00' and LENEMI <> ENEPRO
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01' AND SUBSTR(LIDTRA,1,1) = 'T'
GROUP BY LBINPR,LIDCOM--,lcodbc,LBCOCR,LBCOCR,LENEMI
ORDER BY LBINPR,LIDCOM;--,lcodbc,LBCOCR,LBCOCR,LENEMI;

-- ADM OPMCATM
SELECT CATARJE AS BIN,CACOMER,/*CAENEMI,CAPROCE,CACODAD,*/
SUM(CACANAD) AS CANTIDAD,SUM(CAIMPOR) IMPORTE
from GXOPERA.OPMCATM
WHERE SUBSTR(CAFECHA,1,8) = '20210201'--01' 
AND CACODAD = '002'
--AND CAMARCA = 'MST'--'MST' 
AND CAMARCA = 'VSA'
AND CAPROCE IN ('510','550')
--AND CAPROCE IN ('530')
AND CAENEMI <> '002'
group by  CATARJE,CACOMER--,CAENEMI,CAPROCE,CACODAD
ORDER BY CATARJE,CACOMER;--,CAENEMI,CAPROCE,CACODAD;--24
--####################### PROPIETARIO
SELECT CATARJE AS BIN,CACOMER,/*CAENEMI,CAPROCE,CACODAD,*/
SUM(CACANAD) AS CANTIDAD,SUM(CAIMPOR) IMPORTE
from GXOPERA.OPMCATM
WHERE SUBSTR(CAFECHA,1,8) = '20210201'--01' 
AND CACODPR = '002'
--AND CAMARCA = 'MST'
AND CAMARCA = 'VSA'
AND CAPROCE IN ('510','550')
--AND CAPROCE IN ('530')
AND CAENEMI <> '002'
group by  CATARJE,CACOMER--,CAENEMI,CAPROCE,CACODAD
ORDER BY CATARJE,CACOMER;--,CAENEMI,CAPROCE,CACODAD;--40

---------------- ENTIDAD 070 MES ABRIL 04
SELECT * FROM VIRGILILIB.OPMmarc WHERE MACOBC = 'VSA';
SELECT * FROM VIRGILILIB.OPMTARI WHERE TAENADM = '002' AND TAMARCA = 'VSA';
SELECT * from virgililib.OPMCATM;
--PARA CREDITO PARA ADM
SELECT CATARJE AS BIN,CATIPTA,CACOMER,CAMARCA, SUM(CACANAD) AS CANTIDAD,SUM(CAIMPOR) IMPORTE
from virgililib.OPMCATM
WHERE SUBSTR(CAFECHA,1,6) = '202104'--01' 
AND CACODAD = '070'
AND CAMARCA = 'VSA'--'MST' 
AND CAPROCE IN ('550','510')--'530' 
AND CAENEMI <> '070'
AND CATIPTA = 'CRE'
group by  CATARJE,CACOMER,CATIPTA,CAMARCA
ORDER BY CATARJE,CACOMER,CATIPTA,CAMARCA;

--PARA PROPIETARIO
SELECT CAPROCE,CAMARCA, SUM(CACANPR) AS CANTI_PR,SUM(CAIMPOR) IMPORTE
from virgililib.OPMCATM
WHERE SUBSTR(CAFECHA,1,6) = '202104'--01' 
AND CACODPR = '070'
AND CAMARCA = 'VSA'--'MST' 
AND CAPROCE IN ('550','510')--'530' 
AND CAENEMI <> '070'
AND CATIPTA = 'CRE'
group by CAPROCE,CAMARCA
ORDER BY CAPROCE,CAMARCA;
select * from virgililib.opmmarc;


select CAFECHA,count(*) from gxopera.OPMCATM where cafecha = '20210201'
group by  CAFECHA;-- 3.870
--substr(cafecha,1,6) = '202102';

select CAFECHA,count(*) from virgililib.OPMCATM where cafecha = '20210201'
group by  CAFECHA;--4.757



-------------*************************************************
--POR FECHA EN drconbep
Select lfectr,count(*)--ENEADM, 'ADM', LCODBC, LBCOCR, /*LIDCOM, LBINPR,*/ SUBSTR(LCODTR, 1, 2),/* ENEPRO,*/ LENEMI, count(*), SUM(LIMPGS)
from gxopera.drconbep
where lfectr between '20210201' and '20210201' and lcodbc = 'MST' and LBCOCR = '530' and ENEADM = '087'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00' and LENEMI <> ENEPRO
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01' --and ENEADM = '002'
GROUP BY lfectr;--,ENEADM, LCODBC, LBCOCR,/* LIDCOM, LBINPR,*/ SUBSTR(LCODTR, 1, 2), /*ENEPRO,*/ LENEMI

--- CANTIDAD EN MST EN DRCONBEP
Select LCODBC,LBCOCR,COUNT(*)
from virgililib.drconbep
where lfectr between '20210201' and '20210201' 
and lcodbc = 'MST' and LBCOCR = '530' and ENEADM = '087'
and SUBSTR(DIGITS(lidcom), 6, 2) = '90' and lcretr = '00' and LENEMI <> ENEPRO
and lesttr = 'A' and substr(lcodtr, 1, 2) = '01'
GROUP BY LCODBC,LBCOCR;

--- CANTIDAD EN MST Y  VSA EN OPMCATM ----> 


SELECT CAMARCA,'PRO', CAPROCE,SUM(CACANPR) CANTIDAD
from GXOPERA.OPMCATM
WHERE SUBSTR(CAFECHA,1,8) = '20210201' 
AND CACODPR = '087'
AND CAMARCA = 'VSA' 
AND CAPROCE IN ('540', '015') --'530'
AND CAENEMI <> '087' 
group by CAMARCA,CAPROCE; --3.086
