select * from gxtrjdta.TDGENT
select * from gxtrjdta.TCOEAC
select * from gxtrjdta.TCOENC
select * from gxtrjdta.TDGENM
select * from gxtrjdta.TDGEMD
select * from gxtrjdta.TDGEMP
select * from gxtrjdta.TDGENR
select * from gxtrjdta.TDGENS
select * from gxtrjdta.TDGAFI
select * from gxtrjdta.TDGADF
select * from gxtrjdta.TDGALC
select * from gxtrjdta.TDGAMC
select * from gxtrjdta.TDGATI
select * from gxtrjdta.TDGBIN
select * from gxtrjdta.TDGMAR
select * from gxtrjdta.TDGMPR
select * from gxtrjdta.TDGPRO
select * from gxtrjdta.TCAFUE
select * from gxtrjdta.TCASCO
select * from gxtrjdta.TCASFU
select * from gxtrjdta.TCAREC
