select * FROM libdebito.tbcret0p --MAESTRO DE CODIGOS DE RESPUESTAS

SELECT * FROM GXBDBPS.TCOCAT
SELECT * FROM gxbdbps.comaeaf
SELECT * FROM gxopera.clparf 
SELECT * FROM LIBDEBITO.EMBNOVTMD
 
select * from gxbdbps.tmtaraf -- Extractos Tarjetas de Crédito Banco Continental- Entidad 021- Orden de no impresion
where enemiso='021' and MTSTATS='1' and mtreten<>'N'

SELECT * FROM LIBDEBITO.TBCTRA0P WHERE TXDTRX LIKE '%SALARIO%' --MAESTRO DE CODIGOS DE TRX

SELECT * FROM GXBDBPS.GENTIAF WHERE ENNOMBR LIKE '%VISION%'

SELECT * FROM GXBDBPS.TAFITRA WHERE COCOMER='0703744' --TABLA DE COMERCIOS ASOCIADOS A LA TARJETA GOURMET 627431155

SELECT * FROM LIBDEBITO.TBINPROC WHERE PBIN LIKE '456979%'

SELECT * FROM LIBDEBITO.TBBINE0P WHERE QEBI10 like '456979%'

SELECT * FROM ATMCENTRE.TBBINE0P WHERE QEBI10 like '627431%'

SELECT * FROM GXTRJDTA.TDGBIN WHERE BINNROBIN LIKE '456976%'

SELECT * FROM @JRNRCVLIB.JRNRCV8713

select * from gxopera.tclsec -- pago en linea de comercios con enemiso 146 pago comercios
