--UPDATE
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ARABIA SAUDÍTA' WHERE PAIIDPAIS=682;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='BAHAMAS' WHERE PAIIDPAIS=44;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='BELARÚS' WHERE PAIIDPAIS=112;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='BONAIRE' WHERE PAIIDPAIS=535;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='BOSNIA Y HERZEGOVINA' WHERE PAIIDPAIS=70;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='BUTÁN' WHERE PAIIDPAIS=64;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='CIUDAD DEL VATICANO' WHERE PAIIDPAIS=336;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='CONGO (BRAZZAVILLE)' WHERE PAIIDPAIS=178;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='CONGO RD' WHERE PAIIDPAIS=180;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='COREA DEL NORTE' WHERE PAIIDPAIS=408;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='COREA DEL SUR' WHERE PAIIDPAIS=410;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='CURAÇAO' WHERE PAIIDPAIS=531;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ESTADOS UNIDOS' WHERE PAIIDPAIS=840;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ESTADOS UNIDOS (ISLAS MENORES ' WHERE PAIIDPAIS=581;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='FIYI' WHERE PAIIDPAIS=242;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='GAMBIA' WHERE PAIIDPAIS=270;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='GEORGIA DEL SUR E ISLAS SANDWI' WHERE PAIIDPAIS=239;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='GUAYANA' WHERE PAIIDPAIS=328;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='GUERNESEY' WHERE PAIIDPAIS=831;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='HAITÍ' WHERE PAIIDPAIS=332;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='INDONESIA' WHERE PAIIDPAIS=360;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='IRÁN' WHERE PAIIDPAIS=364;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS COCOS (KEELING)' WHERE PAIIDPAIS=166;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS COMOROS' WHERE PAIIDPAIS=174;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS COOK' WHERE PAIIDPAIS=184;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS MALVINAS (FALKLAND)' WHERE PAIIDPAIS=238;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS PITCAIRN' WHERE PAIIDPAIS=612;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS VÍRGENES BRITÁNICAS' WHERE PAIIDPAIS=92;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ISLAS VÍRGENES DE EE.UU.' WHERE PAIIDPAIS=850;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='KIRGUISTÁN' WHERE PAIIDPAIS=417;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='LAOS' WHERE PAIIDPAIS=418;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='LESOTO' WHERE PAIIDPAIS=426;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='MACEDONIA' WHERE PAIIDPAIS=807;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='MICRONESIA' WHERE PAIIDPAIS=583;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='MOLDOVA' WHERE PAIIDPAIS=498;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='PAKISTÁN' WHERE PAIIDPAIS=586;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='PALAU' WHERE PAIIDPAIS=585;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='PALESTINA (GAZA)' WHERE PAIIDPAIS=275;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='PANAMÁ' WHERE PAIIDPAIS=591;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='PAPUA NUEVA GUINEA' WHERE PAIIDPAIS=598;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='POLINESIA FRANCÉS' WHERE PAIIDPAIS=258;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='REINO UNIDO' WHERE PAIIDPAIS=826;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='REPÚBLICA CENTROAFRICANA' WHERE PAIIDPAIS=140;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='REPÚBLICA CHECA' WHERE PAIIDPAIS=203;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='REUNIÓN' WHERE PAIIDPAIS=638;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='RUMANIA' WHERE PAIIDPAIS=642;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='RUSIA' WHERE PAIIDPAIS=643;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SÁHARA OCCIDENTAL' WHERE PAIIDPAIS=732;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SAN MARTÍN' WHERE PAIIDPAIS=663;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SAINT-BARTHÉLEMY' WHERE PAIIDPAIS=652;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SAN VICENTE Y LAS GRANADINAS' WHERE PAIIDPAIS=670;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SANTA HELENA - ASCENSIÓN Y TRI' WHERE PAIIDPAIS=654;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SINT MAARTEN' WHERE PAIIDPAIS=534;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SIRIA' WHERE PAIIDPAIS=760;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='SUAZILANDIA' WHERE PAIIDPAIS=748;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='TAIWAN' WHERE PAIIDPAIS=158;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='TERRITORIO BRITANICO DEL OCÉA' WHERE PAIIDPAIS=86;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='TERRITORIOS FRANCESES DEL SUR' WHERE PAIIDPAIS=260;
UPDATE GXTRJDTA.TDGPAI SET PAIDSPAIS='ZIMBABUE' WHERE PAIIDPAIS=716;
UPDATE GXTRJDTA.TDGPAI SET PAIISOALF2='UN' WHERE PAIIDPAIS=570;



--> INSERT
INSERT INTO GXTRJDTA.TDGPAI (PAIIDPAIS,PAIDSPAIS,MONIDMONED,PAIISOALF2,PAIISOALF3,PAIUSULTUP,PAIFHULTUP)
VALUES (895,'ANTILLAS HOLANDESAS',895,'AN','ANT',CURRENT USER,CURRENT TIMESTAMP);

INSERT INTO GXTRJDTA.TDGPAI (PAIIDPAIS,PAIDSPAIS,MONIDMONED,PAIISOALF2,PAIISOALF3,PAIUSULTUP,PAIFHULTUP)
VALUES (896,'KOSOVO',896,'XK','XKX',CURRENT USER,CURRENT TIMESTAMP);

