-----------VARIOS----------------------------
SELECT * FROM LIBDEBITO.DRCONBEP; -- MAESTRO DE TRANSACCIONES
SELECT * FROM GXBDBPS.GENTIAF; -- TABLA DE ENTIDADES
SELECT * FROM LIBDEBITO.TBCTRA0P; -- TABLA DE COD. TRX
SELECT * FROM LIBDEBITO.TBCRET0P; --TABLA DE COD DE RETORNO
select * from libdebito.binprodu WHERE RGBIN='473230';---Tabla de bines
select * FROM visa.VISCTLDTA; -- TARJETAS VISA
select * from GXBDBPS.TAFINAF where AFDESCR LIKE '%COOP.%'; --ENEMISO = '186'= 'conti';--
select * from libdebito.TBINPROC; --BINES DE PROCARD
SELECT * FROM LIBDEBITO.TBBINE0P;--BINES DE BEPSA
SELECT * FROM LIBDEBITO.TC33;  --BINES
select * from gxbdbps.gentiaf where ENEMISO='107';--BANCOS--
select * from gxbdbps.GENTIAF;
SELECT * FROM GXBDBPS.COMAEXD;---TASA POR COMERCIO Y TIPO DE TARJETA

/*Bancos*/
Select * from contabilid.tatgene where TGENTI = '1007 ' AND tgalfa = 'BA';
Select * from gxopera.clparf where PARCODBCO IN ('057','054','057','062','064','065');

select * from gxbdbps.comaeaf where COCOMER in ('2300725','0201059')
and ADNUMCTA = '10082480006';
-- CODENO like '%LA FORTUNA%'
--actual
update gxbdbps.comaeaf set ADNUMCTA ='0626103507' where COCOMER ='0703051'
and ADNUMCTA = '10082480006';
--reing
SELECT * FROM  GXFINDTA.TCMSUC where SUCDENCOM like '%LA FORTUNA%';
Select * from gxtrjdta.tdgbin WHERE BINNROBIN='558039';--Bines
Select * from gxtrjdta.tdgbin where BINNROBIN = '627431';
Select * from gxtrjdta.tdgent; --Entidades

/*TBBINE0P Tabla de bines de POS
TBBINE0PA Tabla de bines de ATM
TDBIN Tabla de bines debito
tdgbin Tabla bines reingenieria*/

select * from GXOPERA.OPENTID1 where REENTI='181';--Entidades
select * from GXOPERA.opentid;  --Entidades
select * from  GXBDBPS.GENTIAF;  --Entidades
select * from  GXWEB.GENTIAF;  --Entidades
select * FROM GXBDBPS.COMAEAF -- comercios
--where COCOMER = '0200878'
where CODENO like '%FOGONERA%';
--lenemis
Select * from gxopera.opentid1
--where ENTBINA like '%JUDIC%' 
where REENTI = '0146'
order by REENTI asc;

select * from gxbdbps.gentiaf 
--where ENNOMBR like '%JUDIC%'
where ENEMISO='512'
order by ENEMISO asc;

"0010"	"WALLY"
"0009"	"ZIMPLE"
"0005"	"TIGO"
"0007"	"PERSONAL"
"0008"	"CLARO"

SELECT * FROM GXBDBPS.TBINEXT WHERE EXTBIB='473230 '; --INTERMEDIA--DB2
SELECT * FROM GXBDBPS.ATDBIN WHERE BBIN='473230 '; --PARAMETRICA--DB2
SELECT * FROM LIBDEBITO.BDBNFBIN0P WHERE QEBINE=''; --PARAMETRICA--DB2
SELECT * FROM LIBDEBITO.BINPRODU WHERE RGBIN=''; --PARAMETRICA--DB2
SELECT * FROM PUBLIC.BINRANGE WHERE start/end=''; --PARAMETRICA--POSTGRESQL
SELECT * FROM LIBDEBITO.CNXBIN0P WHERE QEBIN1=''; --PARAMETRICA--DB2
SELECT * FROM MASTERCARD.MASSIMDTA WHERE MA002='473230 '; --PARAMETRICA--DB2
SELECT * FROM GXBDBPS.NUT007 WHERE MTARDBINID=''; --PARAMETRICA--DB2
SELECT * FROM GXOPERA.OPENTID1 WHERE ENTBIN=''; --PARAMETRICA--DB2
SELECT * FROM ATMCENTRE.TBBINE0P WHERE QEBI10='473230'; --PARAMETRICA--DB2
SELECT * FROM LIBDEBITO.TBBINE0P WHERE QEBI10='473230 '; --PARAMETRICA--DB2
SELECT * FROM GXBDBPS.TBINEAF WHERE BIBINES='473230 '; --PARAMETRICA--DB2
SELECT * FROM GXBDBPS.TDBIN WHERE TDBINNRO='473230 '; --PARAMETRICA--DB2
SELECT * FROM GXBDBPS.TDBINDET WHERE TDBINNRO=''; --PARAMETRICA--DB2
SELECT * FROM GXBDBPS.TDBINEMB WHERE TDENTBIN=''; --PARAMETRICA--DB2
SELECT * FROM GXTRJDTA.TDGBIN WHERE BINNROBIN=''; --PARAMETRICA--DB2
SELECT * FROM VISA.ACFIRECD WHERE FI87535=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.AIT002 WHERE AITCAUTCOD=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.AIT002 WHERE AITCAUTCOD=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.AITINC45 WHERE I45_BINE=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.AITINC45E WHERE I45_BINE=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.AITINC45T WHERE I45_BINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.ATMCMSGLOG WHERE MSGLDE038=''; --TRANSACCIONAL--DB2
SELECT * FROM FEATMSLIB.AUCTB WHERE CTBBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.AUTVOZ WHERE VBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.AUTVOZA WHERE VBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.AUTVOZH WHERE VBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.AUTVOZL1 WHERE VBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.AUTVOZL2 WHERE VBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM FEATMSLIB.AZKBIN WHERE BINBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM FEATMSLIB.AZKRBL WHERE RBLBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BBBNF1 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNF27 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFDATOS WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFDATOZ WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.BDBNFENHXX WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENV0H WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENV0P WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENV0X WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENV0Z WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.BDBNFENV17 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENVOX WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFENVZ WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDBNFVER0P WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.BDCONBJB14 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.BDCONBJC14 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.BDPOLICIA WHERE REFDOC=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.BST007 WHERE BS07BINPRO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXWEB.BST007 WHERE BS07BINPRO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.CARDRANGES WHERE BINHI=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CLCONBEP WHERE CBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CLEFIN0P WHERE CLBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CLEFIN0PZ WHERE CLBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CNXBINL1 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.COMVTM0PDA WHERE MVBINT=''; --TRANSACCIONAL--DB2
SELECT * FROM JAVAJCF.COMVTM1P WHERE MVBINT=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.COMVTMAF WHERE MVBINT=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CONTRATO WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.CONTRATOS WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CTAKREP WHERE AKACNB=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CTAKREPCS WHERE AKADCD=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CTAKREPL1 WHERE AKACNB=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CTAOREP WHERE AOADCD=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.CTAOREPL1 WHERE AOADCD=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DCTRANS WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.DEBUGVISA WHERE DEBUGDATA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DRC151213 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DRC151213E WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DRC151213G WHERE BS07BINPRO=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DRC151213W WHERE BS07BINPRO=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.DRCON10A12 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.DRCON1202 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXWEB.DRCON180 WHERE ALBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.DRCONBIN WHERE TBBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.DRCONBJC14 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.DRCONBLUIS WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.DRCONPEDRO WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.DRCONTRA WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXOPERA.DRCPY3007 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.DTWFIN0P WHERE CLBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.DWHFINAF WHERE CLBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.DWHFINAFXP WHERE CLBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMB200802 WHERE BINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMB200802B WHERE BINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTL1 WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTL2 WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTL3 WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTL4 WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTL5 WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBHSTNE WHERE HSNCTA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBMAETMP WHERE EZBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBNOVHSCP WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBNOVHST WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBNOVHSTX WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.EMBOZA06 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBSTK0001 WHERE ENBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBSTKAF WHERE ENBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBSTKMN WHERE MNBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.EMBTRKHST WHERE TKBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ENTFIL001 WHERE ENTENTIDA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ENVPROA11 WHERE LCAUTR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ERCONBEP WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXOPERA.FACENTI WHERE FACTBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.FACTENTI WHERE BIN=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.GXA0007 WHERE BIN=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.HEMBTRKHST WHERE HTKBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.IIPMDTE4 WHERE IPMDEV=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.IIPMDTE5 WHERE IPMDEV=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.IMCT464D WHERE T464FRAUCO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.IMCTN70D WHERE TN70CODAPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.IPMDTAE WHERE IPMDEV=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.IPMDTAE WHERE IPMDEV=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.IPSNOV WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXTRJDTA.ITDGBIN WHERE BINNROBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.ITMIFDT WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.ITSWAUT WHERE AUTBINEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.ITSWAUT WHERE AUTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.LOGMOV0P WHERE ENCODA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.LOGMOVBNF WHERE ENCODA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.LOGMOVL2 WHERE ENCODA=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.LOGSER0P WHERE ENCODA=''; --TRANSACCIONAL--DB2
SELECT * FROM ROSHKALIB.M_MED000L1 WHERE BIN_EMISOR=''; --TRANSACCIONAL--DB2
SELECT * FROM ROSHKALIB.M_MED000L6 WHERE BIN_EMISOR=''; --TRANSACCIONAL--DB2
SELECT * FROM ROSHKALIB.M_MEDIOS_PAGO WHERE BIN_EMISOR=''; --TRANSACCIONAL--DB2
SELECT * FROM ROSHKALIB.M_MEDIOS_PAGO_EMISORES WHERE BIN_EMISOR=''; --TRANSACCIONAL--DB2
SELECT * FROM MASTERCARD.MASCTLDTA WHERE MC011='473230'; --TRANSACCIONAL--DB2
SELECT * FROM MASTERCARD.MASCTLDTAL WHERE MC011='473230 '; --TRANSACCIONAL--DB2
SELECT * FROM MASTERCARD.MASTRNDTA WHERE MCCOMCOD='473230 '; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.MCT464FRDR WHERE T464FRAUCO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.MCT464FRDR WHERE T464FRAUCO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.MCTN70D WHERE TN70CODAPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.MECNOV WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.NOVEDADES WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ONHL101 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ONHL102 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ONHP001 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ONHP001L1 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.ONHP001L2 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.OPEMAEHST WHERE RBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.OPEMAEHSTB WHERE RBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.OPEMAEHSTN WHERE RBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.PASAR WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.PINLIMIT WHERE PINLIMBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.PRUEBADDM WHERE TCBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.PRUEBCLR WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.PRUEBCLR28 WHERE LBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM BDDEBITO.STPROVAF WHERE PRBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.STPROVAF WHERE PRBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.SUC02 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.SUC04 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.SUC16 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBPASAR.SUC46 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TAHRPIN WHERE THBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TAUREV WHERE REVBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.TAUTPAF WHERE APCODAU=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.TAUTPAFL1 WHERE APCODAU=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINE0PB1 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINE0PXP WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINE0PZ WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINEL1 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINEL2 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINEL3 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM ATMCENTRE.TBBINEL5 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBBINEL5 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM GXFINDTA.TBDAUD WHERE AUDBINEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTA0P WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTA0PXP WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTAL1 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTAL2 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTAL3 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TBRUTAL5 WHERE QEBIN1=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TC33 WHERE TCBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXFINDTA.TCLHTM WHERE HTMBEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM GXFINDTA.TCLMOV WHERE MOVCOAU=''; --TRANSACCIONAL--DB2
SELECT * FROM GXOPERA.TCLSEC WHERE SECENBIN=''; --TRANSACCIONAL--DB2
SELECT * FROM GXFINDTA.TCLTPC WHERE TPCBEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.TCONTRATOS WHERE EMBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXOPERA.TDAVISTAS WHERE TDABIN=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.TDEMNOTAR WHERE NEBINNRO=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.TDMOV WHERE MOVAUTCOD=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.TGCLASAF WHERE BINCODIG=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.TGCLASL1 WHERE BINCODIG=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEBMNOVB1 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEBMNOVB2 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEBMNOVBN WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMB2406 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBDJFC WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBERR WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBH0001 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBHAF WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.TGEMBHAFYY WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBNO257 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBNOVXX WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBNOVZ WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILSE.TGEMBNOXX WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMP14 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMP19 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMP24 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMP9 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB1 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB2 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB3 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB4 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB5 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB6 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB7 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB8 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPB9 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM QGPL.TGEMBTMPBX WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC2 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC3 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC4 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC5 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC6 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM SMILBKP.TGEMBTMPC9 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD1 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD2 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD3 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD4 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD5 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD6 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD7 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPD9 WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TGEMBTMPZ WHERE CRBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.TGMTABNF WHERE BINCODIG=''; --TRANSACCIONAL--DB2
SELECT * FROM GXDEBITO.THENSUAF WHERE ENBINE=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.THMOVAF WHERE HMCODAU=''; --TRANSACCIONAL--DB2
SELECT * FROM GXBDBPS.TLOGTAF WHERE LTCODAU=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.TMIFDT WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.TRSREV0P WHERE TRBINPR=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBCLEA.TSWAUT WHERE AUTBINEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UAIT0023 WHERE AITCAUTCOD=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UIPMDTAE WHERE IPMDEV=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UMCTN701 WHERE TN70CODAPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UMTN70D1 WHERE TN70CODAPR=''; --TRANSACCIONAL--DB2
SELECT * FROM GXFINDTA.UTCLTPC WHERE TPCBEMI=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UTMIFDT1 WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UTMIFDT2 WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UTMIFDT3 WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM GXSWTDTA.UTMIFDT4 WHERE FDTCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM MASTERCARD.VIEWMASTRXCON WHERE BIN='558039'; --TRANSACCIONAL--DB2
SELECT * FROM VISA.VIEWTRXCON WHERE VCODAUT=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.VISCTLDTA WHERE V011=''; --TRANSACCIONAL--DB2
SELECT * FROM VISA.VISTRNDTA WHERE VICOMCOD=''; --TRANSACCIONAL--DB2
SELECT * FROM LIBDEBITO.VMPFDAT WHERE VMPFCAUT=''; --TRANSACCIONAL--DB2
