SELECT
	DISTINCT t.AUTPANNRO,
	t.AUTCODCOMB,
	t.AUTBINEMI,
	TRIM(t.AUTRRNBEP) referencia,
	t.AUTMARTAR,
	t.AUTTIPTAR,
	t.AUTPROTAR,
	t.AUTTRXFCHF,
	d.LHORTR,
	t.AUTTRXFCHC "fecha_comercial",
	t.AUTDISTIP,
	t.AUTTRXESTF,
	t.AUTCODRET,
	d.LESTTR,
	d.LCRETR,
	t.AUTCOMRAZ,
	t.AUTMONTDES,
	t.AUTESTCLE,
	t.AUTCODSER ,
	t.AUTCODPRE,
	o.OPENEMI,
	t2.MOVPGON ,
	o.OPNOREF,
	(opmonto-opcomi-oprenta-opreiva) neto ,
	CASE
	WHEN t2.MOVRRNBEP IS NULL THEN 'NULL'
	ELSE t2.MOVRRNBEP
	END	MOVRRNBEP,
	t2.MOVIDLT,
	t2.MOVNETO,
	o2.OPIDLIQ "id_opliqui",
	o2.OPCODBCO,
	s.TSBIMPO ,
	s.TSBDEME ,
	dd.RTCIDRETEN ,
	OPSTAT,
	OPSTATOB,
	d.LHISDE,
	CASE
		WHEN (
		SELECT
			count(1)
		FROM
			GXOPERA.TCLSEC s
		WHERE
			d.lenemi = s.seccoem
			AND substring(d.lnrtar, 1, 6) = substring(s.SECENBIN, 1, 6)
			AND d.lcodtr = s.SECCOTRX) > 0 THEN 'ONLINE'
		ELSE 'BATCH'
	END tipo_op,
	CASE
		WHEN o.OPNOREF IS NULL THEN 'NO_OPMOVI'
		ELSE 'OK_OPMOVI'
	END SITU_OPMOVI,
	CASE
		WHEN OPIDLIQ IS NULL THEN 'NO_LIQUIDADA'
		ELSE 'LIQUIDADA'
	END SITU_OPLIQUI,
	CASE
		WHEN o2.OPCODBCO = 57
		AND s.TSBIMPO IS NULL
		AND dd.RTCIDRETEN IS NULL
		AND OPSTAT = '00'
		AND OPSTATOB = '00'
		AND TRIM(LHISDE) = '*BNF' THEN 'A_PAGAR'
		WHEN o2.OPCODBCO = 57
		AND s.TSBIMPO IS NULL
		AND dd.RTCIDRETEN IS NULL
		AND TRIM(LHISDE) <> '*BNF' THEN 'A_PAGAR'
		ELSE 'NO_PAGAR'
	END SITU_PAGAR,
	'PENDIENTE' estado_pgm28,
	'PENDIENTE' estado_pgm29,
	CURRENT_TIMESTAMP hora_ejecucion
	,'0' "intentos" 
FROM
	GXBDBPS.TSWAUT t
LEFT JOIN GXBDBPS.COMAEAF c ON
	t.AUTCODCOMB = c.COCOMER
LEFT JOIN GXFINDTA.TCLMOV t2 ON
	t.AUTRRNBEP = t2.MOVRRNBEP
LEFT JOIN GXFINDTA.TCLTSB s ON
	t2.MOVIDLT = s.TSBNREF
	OR t.AUTRRNBEP = s.TSBNREF
LEFT JOIN GXOPERA.OPMOVI o ON
	t.AUTRRNBEP = o.OPNOREF
	AND o.OPSTATUS = 'A'
LEFT JOIN GXOPERA.OPLIQUI o2 ON
	o2.OPNROREF = t.AUTRRNBEP
LEFT JOIN gxopera.OPLICRE o3 ON
	o3.OPCREID = t2.MOVIDLT
LEFT JOIN GXFINDTA.TCLIMB t3 ON
	t3.IMBLOT = t2.MOVIDLT
LEFT JOIN LIBDEBITO.DRCONBEP d ON
	d.LERRNB = t.AUTRRNBEP
LEFT JOIN GXFINDTA.TCLRTD dd ON
	dd.MOVIDMOV = t2.MOVIDMOV
WHERE
	--AUTRRNBEP = '309669864262' 
	t.AUTTRXFCHC >= ? --BETWEEN '20230103' AND '20230103'
	--AND c.CORUCN = '80016096-7' 
	--AND d.LHORTR BETWEEN '0' AND '235959'
	--AND t.AUTRRNBEP IN () 
	AND trim(t.AUTDISTIP) = 'POS'
	AND t.AUTTRXESTF = 'A'
	AND t.AUTCODRET = '00'
	AND d.LESTTR = 'A'
	AND d.LCRETR = '00'
	--AND t.AUTESTCLE = 'P' 
	AND t.AUTMONTDES > 0
	AND TRIM(t.AUTMARTAR) NOT IN ('CAB' , 'PAN')
	AND t.AUTCODCOMB NOT IN ('6900282', '6900296', '6900281', '0100001')
	AND trim(t.AUTCODSER) NOT IN ('DEPOATM', 'CONSULTA', 'TRANSFER', 'CAMPIN', 'CIERRE')
	AND TRIM(AUTCODPRE) NOT IN ('COPU')
	AND (
	CASE
		WHEN (
		SELECT
			count(1)
		FROM
			GXOPERA.TCLSEC s
		WHERE
			d.lenemi = s.seccoem
			AND substring(d.lnrtar, 1, 6) = substring(s.SECENBIN, 1, 6)
				AND d.lcodtr = s.SECCOTRX
			) > 0 
			THEN 'ONLINE'
		ELSE 'BATCH'
	END
	) = 'ONLINE'
	-- solo las online 
	AND dd.RTCIDRETEN IS NULL
	-- NO estan retenidas 
	AND o.OPNOREF IS NOT NULL
	-- debe estar en opmovi 
	--AND t2.MOVRRNBEP IS NULL 
	WITH UR