--SIRIUS
select spv.idempresa, spv.idsisparam, sp."key", spv.value from base.sis_param_value spv
join base.sis_param sp on sp.idsisparam = spv.idsisparam
where idempresa = 2;

SELECT * FROM BASE.SIS_PARAM_VALUE SPV
WHERE IDEMPRESA= 2
--CODIGO SECRETO BEPSA  ef3b2C19F0ec19e9CA973cf72ACed398
SELECT * from base.sis_param_value WHERE IDEMPRESA='2';
UPDATE BASE.SIS_PARAM_VALUE
SET VALUE = 'ef3b2C19F0ec19e9CA973cf72ACed398'::VARCHAR(200)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSISPARAM = 15::INTEGER;
  UPDATE BASE.SIS_PARAM_VALUE
SET VALUE = 'https://ekuatia.set.gov.py/consultas/qr?'::VARCHAR(200)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSISPARAM = 16::INTEGER;
UPDATE BASE.SIS_PARAM_VALUE
SET VALUE = 'ef3b2C19F0ec19e9CA973cf72ACed398'::VARCHAR(200)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSISPARAM = 22::INTEGER;
  UPDATE BASE.SIS_PARAM_VALUE
SET VALUE = 'https://sifen.set.gov.py'::VARCHAR(200)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSISPARAM = 62::INTEGER;
--TIMBRADO PRODUCCION 16410772
select * from sifen.empresa e ;
UPDATE SIFEN.EMPRESA
SET NOMBREFANTASIA = 'BEPSA SAECA'::VARCHAR(60)
WHERE IDEMPRESA = 2::INTEGER;
UPDATE SIFEN.EMPRESA
SET CORREO = 'CONTABILIDAD@BEPSA.COM.PY'::VARCHAR(80)
WHERE IDEMPRESA = 2::INTEGER;

--TRIGER PARA CAMBIAR NOMBRE DE FANTASIA, DISBLED PARA HABILITAR PARA CAMBIAR Y LUEGO ENABLED
ALTER TABLE sifen.empresa DISABLE TRIGGER tiu_sifen_valid_empresa;

select * from sifen.empresatimbrado e ;
SELECT * FROM SIFEN.EMPRESASUCURSALCAJA E; -- SE CREA UNA CAJA NUEVA
INSERT INTO SIFEN.EMPRESASUCURSALCAJA (IDEMPRESA, IDSUCURSAL, IDCAJA, DESCRIPCION, CODIGO, AUD_FECALTA, AUD_FECMODIF, AUD_IDUSUARIOALTA, AUD_IDUSUARIOMODIF)
VALUES (2::INTEGER, 1::INTEGER, 2::INTEGER, 'CAJA 2'::VARCHAR, 'CAJA2'::VARCHAR(5), NULL::TIMESTAMP, NULL::TIMESTAMP, NULL::INTEGER, NULL::INTEGER);

SELECT * FROM SIFEN.EMPRESATIMBRADO E; -- PARA FACTUARA ELECTRONICA
UPDATE SIFEN.EMPRESATIMBRADO
SET PUNTOEXPEDICION = 2::NUMERIC(3)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSUCURSAL = 1::INTEGER
  AND IDCAJA = 1::INTEGER
  AND IDTIPODOCUMENTOELECTRONICO = 1::INTEGER
  AND IDEMPRESATIMBRADO = 1::INTEGER;
--se agrega una linea nueva
INSERT INTO SIFEN.EMPRESATIMBRADO (IDEMPRESA, IDSUCURSAL, IDCAJA, IDTIPODOCUMENTOELECTRONICO, IDEMPRESATIMBRADO, NUMEROTIMBRADO, ESTABLECIMIENTO, MASCARAESTABLECIMIENTO, PUNTOEXPEDICION, MASCARAPUNTOEXPEDICION, MASCARANROFACTURA, MASCARASEPARADOR, INIVIGENCIA, FINVIGENCIA, ACTIVO, AUD_FECALTA, AUD_FECMODIF, AUD_IDUSUARIOALTA, AUD_IDUSUARIOMODIF)
VALUES (2::INTEGER, 1::INTEGER, 2::INTEGER, 1::INTEGER, 1::INTEGER, 12560254::NUMERIC(8), 1::NUMERIC(3), '##0'::VARCHAR(10), 3::NUMERIC(3), '##0'::VARCHAR(10), '######0'::VARCHAR(20), '-'::VARCHAR(1), '2022-12-22'::DATE, NULL::DATE, TRUE::DO_BOO_ACTIVO, NULL::TIMESTAMP, NULL::TIMESTAMP, NULL::INTEGER, NULL::INTEGER);
--timbrado
UPDATE SIFEN.EMPRESATIMBRADO
SET NUMEROTIMBRADO = 16410772::NUMERIC(8)
WHERE IDEMPRESA = 2::INTEGER
  AND IDSUCURSAL = 1::INTEGER
  AND IDCAJA = 1::INTEGER
  AND IDTIPODOCUMENTOELECTRONICO = 2::INTEGER
  AND IDEMPRESATIMBRADO = 2::INTEGER;
--vigencia
UPDATE SIFEN.EMPRESATIMBRADO
SET INIVIGENCIA = '2023-05-17'::DATE
WHERE IDEMPRESA = 2::INTEGER
  AND IDSUCURSAL = 1::INTEGER
  AND IDCAJA = 1::INTEGER
  AND IDTIPODOCUMENTOELECTRONICO = 7::INTEGER
  AND IDEMPRESATIMBRADO = 4::INTEGER;
select * from sifen.tipoactividadeconomica t   ;
select * from sifen.empresatipoactividadeconomica e;
select * from sifen.documentoelectronico d ; --PARA IDDTO 3201069
SELECT * FROM INTEGRACION.DTO D WHERE IDDTO='3201069';
select * from base.usuario u;
UPDATE BASE.USUARIO
SET CORREO = 'producciontic@bepsa.com.py'::VARCHAR(100)
WHERE IDUSUARIO = 5638::INTEGER;
-----------------------------------------------------------------------------
SELECT * FROM BASE.USUARIO U
