
-- =============================PMOV005
SELECT * FROM GXTRJDTA.TDGTCA; -- CARGOS 

SELECT * FROM GXTRJDTA.TDGTSA; -- SALDOS

SELECT * FROM GXTRJDTA.TTCCMS; -- CUENTAS SALDO  

SELECT * FROM GXTRJDTA.TTCCta WHERE CTAIDCTA = '041400000026'  ;  -- CUENTAS TARJETAS DE CREDITO

SELECT * FROM GXTRJDTA.TTCCDF WHERE CTAIDCTA = '041400000026'; --cUENTAS A SER AFECTADAS 




