/*================================================PCON014============================================*/
	SELECT SUBSTRING(AUXCLAV,1,3),SUBSTRING(AUXCLAV,4,6),SUBSTRING(AUXCLAV,10,3),AUXEST FROM GXTRJDTA.TCOAUX  WHERE  AUXTBL='TAFINAF   ';

	SELECT * FROM GXBDBPS.TAFINAF; 

	SELECT * FROM GXBDBPS.TAFINAF INNER JOIN  	GXTRJDTA.TCOAUX ON	ENEMISO = SUBSTRING(AUXCLAV,1,3) AND BIBINES = SUBSTRING(AUXCLAV,4,6) AND AFAFINI = SUBSTRING(AUXCLAV,10,3);

	SELECT * FROM GXTRJDTA.TDGALC;
/*================================================PCON007============================================*/
	SELECT * FROM GXTRJDTA.TATDKB

	
/*================================================PCON017============================================*/
SELECT count(/*AUXTBL, SUBSTRING(AUXCLAV,1,4),SUBSTRING(AUXCLAV,5,3),SUBSTRING(AUXCLAV,8,15),AUXEST ,AUXACCI*/*) FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDCLIENTE' AND AUXEST  = 'P';

SELECT AUXTBL, SUBSTRING(AUXCLAV,1,4),SUBSTRING.
AUXACCI (AUXCLAV,5,3),SUBSTRING(AUXCLAV,8,15),SUBSTRING(AUXCLAV,23,2)  FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDCLIENTED';

SELECT COUNT(*) /*, AUXTBL, SUBSTRING(AUXCLAV,1,3),SUBSTRING(AUXCLAV,4,1),SUBSTRING(AUXCLAV,5,15)*/ FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'GCLIEAF';

SELECT /*AUXTBL, SUBSTRING(AUXCLAV,1,3),SUBSTRING(AUXCLAV,4,1),SUBSTRING(AUXCLAV,5,15),SUBSTRING(AUXCLAV,20,2)*/  FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'GDIREAF';
/* INNER JOIN */


SELECT cOUNT (*) FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDCLIENTED';
SELECT * FROM GXTRJDTA.TDGENP;
SELECT * FROM GXTRJDTA.TDGPER;


/*================================================PCON011============================================*/
SELECT AUXTBL, SUBSTRING(AUXCLAV,1,4),SUBSTRING(AUXCLAV,5,6),SUBSTRING(AUXCLAV,11,12),AUXEST   FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDCTA';

SELECT * FROM GXBDBPS.TDCTA;

SELECT * FROM GXBDBPS.TDCTA  INNER JOIN  GXTRJDTA.TCOAUX ON 	
SUBSTRING(TDCTANRO,1,14)   =  SUBSTRING(AUXCLAV,11,12) AND TDBINENTID =  SUBSTRING(AUXCLAV,1,4) AND TDBINNRO   =  SUBSTRING(AUXCLAV,5,6);

SELECT * FROM GXTRJDTA.TTDCDb;

UPDATE   GXTRJDTA.tcoaux SET AUXEST = 'N'

SELECT *  FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDCTA' AND AUXACCI = 'I';

/*================================================PCON013============================================*/
SELECT AUXTBL, SUBSTRING(AUXCLAV,1,4),SUBSTRING(AUXCLAV,5,6),SUBSTRING(AUXCLAV,11,1),SUBSTRING(AUXCLAV,12,1),SUBSTRING(AUXCLAV,13,12), AUXEST ,AUXACCI FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDEMIS';

SELECT * FROM GXBDBPS.TDEMIS  INNER JOIN  GXTRJDTA.TCOAUX ON 	
SUBSTRING(TDCTANRO,1,14)   =  SUBSTRING(AUXCLAV,13,12) AND TDBINENTID =  SUBSTRING(AUXCLAV,1,4) AND TDBINNRO   =  SUBSTRING(AUXCLAV,5,6);

SELECT *FROM GXTRJDTA.TTDEMI;

/*================================================PCON015============================================*/
SELECT AUXTBL, SUBSTRING(AUXCLAV,1,12) FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TMCTAAF';

SELECT * FROM GXBDBPS.TMCTAAF  INNER JOIN  GXTRJDTA.TCOAUX ON 	
SUBSTRING(AUXCLAV,1,12)  = MCNUMCT  AND AUXTBL = 'TMCTAAF' ;

SELECT  * FROM GXTRJDTA.TTCCta;
SELECT  * FROM GXTRJDTA.TTCCDF;
SELECT  * FROM GXTRJDTA.TTCCLC;
UPDATE   GXTRJDTA.tcoaux SET AUXEST = 'N';
/*================================================PCON003============================================*/
SELECT COUNT(*)  FROM GXTRJDTA.TCOAUX  WHERE  AUXTBL='TMTARAF   ' and AUXEST = 'P';

SELECT * FROM GXBDBPS.TMTARAF INNER JOIN  GXTRJDTA.TCOAUX ON MTNUMTA = AUXCLAV WHERE  AUXTBL='TMTARAF   ' and AUXEST = 'P'	 ;

SELECT * FROM GXTRJDTA.TTCTrj INNER JOIN  GXTRJDTA.TCOAUX ON TrjNroTrj = AUXCLAV	 WHERE  AUXTBL='TMTARAF   ' and AUXEST = 'P'	  ; 



--===========================================PCON036===========================================




SELECT * FROM GXTRJDTA.TCOAUX WHERE (AUXTBL ='TMOVIAF'  OR  AUXTBL ='TMO1MAF' )AND ( AUXACCI = 'I')  ; 

SELECT * FROM GXTRJDTA.TCOAUX WHERE (AUXTBL ='TMOVIAF'  OR  AUXTBL ='TMO1MAF' ) AND AUXEST = 'P';

SELECT * FROM GXTRJDTA.TDSPRC WHERE MODIDMODUL= 'CO';

--update  GXTRJDTA.TDSPRC SET PRCESTADO = 'I'  WHERE MODIDMODUL= 'CO' AND PRCIDPROCE <> 'PCON036' ;
SELECT * FROM GXTRJDTA.TMOMEP;
SELECT * FROM GXTRJDTA.TDSDPS;
SELECT * FROM GXTRJDTA.TDSPWS

SELECT * FROM LIBC.TDSPRC;

	