SELECT * FROM GXFINDTA.TCLPRC;
 



/*SELECT  * FROM GXTRJDTA.TDSDPS  ;

SELECT *  FROM GXTRJDTA.TTDEMI;*/

SELECT SUBSTRING(AUXCLAV,1,4) ENTIDAD ,SUBSTRING(AUXCLAV,5,6) BINNRO,SUBSTRING(AUXCLAV,11,1) TDADHCTAC ,SUBSTRING(AUXCLAV,12,1) CUENTA , SUBSTRING(AUXCLAV,13,12)  CUENTA  FROM GXTRJDTA.TCOAUX WHERE AUXTBL ='TDEMIS'

SELECT *  FROM  GXBDBPS.TDEMIS WHERE TDCTANRO = 1002 AND TDBINENTID  = ;


SELECT * FROM GXBDBPS.TDEMIS /*WHERE TDBINENTID =1002 AND TDCTANRO = 2025857 ;*/




SELECT *  FROM GXTRJDTA.TTCCtD;
SELECT SUBSTRING(AUXCLAV,1,4) ENTIDAD ,SUBSTRING(AUXCLAV,5,3) tipodoc,SUBSTRING(AUXCLAV,8,15)nrodoc, AUXTBL ,AUXACCI ,AUXEST FROM  GXTRJDTA.TCOAUX 	where AUXTBL = 'TDCLIENTED' ;
SELECT SUBSTRING(AUXCLAV,1,3) ENTIDAD ,SUBSTRING(AUXCLAV,4,1) tipodoc,SUBSTRING(AUXCLAV,5,15)nrodoc, SUBSTRING(AUXCLAV,20,2)secue,AUXEST, AUXTBL FROM  GXTRJDTA.TCOAUX 	where AUXTBL = 'GDIREAF';
SELECT * FROM GXTRJDTA.TTCCTA WHERE CtaIdTpDoc ='CIP' AND CtaNroDoc ='6634263'   ;

SELECT COUNT(*) FROM  GXBDBPS.TDCLIENTE ;
SELECT  * FROM  GXTRJDTA.TDCLIENTAG 

SELECT * FROM GXTRJDTA.TTCCTA ;


SELECT SUBSTRING(AUXCLAV,1,4) ENTIDAD ,SUBSTRING(AUXCLAV,5,3) tipodoc,SUBSTRING(AUXCLAV,8,15)nrodoc, AUXTBL , AUXACCI , AUXEST FROM  GXTRJDTA.TCOAUX  
INNER JOIN  GXTRJDTA.TTCCTA ON CTANRODOC =SUBSTRING(AUXCLAV,8,15) where AUXTBL = 'TDCLIENTED' ;

SELECT *   FROM  GXTRJDTA.TCOAUX  where AUXTBL = 'TDCLIENTED' 





SELECT COUNT(*) FROM YAPI.TCOAUXAG ;

SELECT COUNT(*) FROM GXTRJDTA.TCOAUX ;
