SELECT *   FROM GXTRJDTA.TCOAUX  A ;

SELECT SUBSTRING(A.AUXCLAV,1,12)    FROM GXTRJDTA.TCOAUX  A WHERE AUXTBL  = 'TCCCTAF';

SELECT *    FROM GXTRJDTA.TCOAUX  A 
LEFT  JOIN GXBDBPS.TCCCTAF B  ON  SUBSTRING(B.KCNUMCT ,0,12)=  SUBSTRING(A.AUXCLAV,1,12) 
WHERE AUXTBL  = 'TCCCTAF' A;


SELECT * FROM gxtrjdta.TTCCDF  INNER JOIN GXTRJDTA.TCOAUX  ON  CTAIDCTA =  SUBSTRING(AUXCLAV,1,12) 
WHERE AUXTBL  = 'TCCCTAF'AND AUXEST = 'N';





SELECT * FROM GXTRJDTA.TCOAUX  A
LEFT JOIN  GXBDBPS.TENTARES   ON   SUBSTRING(AUXCLAV,1,4) = ENTARID
WHERE AUXTBL  = 'TENTARES'  AND AUXEST = 'N';


SELECT * FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TCODEAF'AND AUXEST = 'N';


SELECT * FROM GXTRJDTA.TDSPrc WHERE MODIDMODUL = 'CO' <AND PRCIDPROCE  IN ('PCON003' , 'PCON007','PCON011','PCON013','PCON014','PCON015','PCON017', 'PCON031','PCON032','PCON034','PCON036','PCON040','PCON043','PCON046') ;

UPDATE  GXTRJDTA.TDSPrc SET  PRCESTADO = 'A'  WHERE MODIDMODUL = 'CO' AND PRCIDPROCE  IN ('PCON003' , 'PCON007','PCON011','PCON013','PCON014','PCON015','PCON017', 'PCON031','PCON032','PCON034','PCON036','PCON040','PCON043','PCON046') ;

