SELECT TDOIDTPDOC, PERNRODOC, ENTCODENT, ENPTPPERSO, ENPNOMBRE1, ENPNOMBRE2, ENPAPELLI1, ENPAPELLI2, ENPRUC, ENPVALIRUC, ENPRAZSOC, ENPDENCOM, ENPIDTPPJU, ENPTPFIRMA, ENPSEXO, ENPIDESTCI, ENPFECNAC, ENPNACIO, ENPNMCORTO, ENPNMLARGO, ENPIDOCUPA, ENPIDPAIS, ENPIDDEPT, ENPIDCIUD, ENPIDBARR, EZNIDZONA, ENPDIRECCI, ENPEMAIL, ENPTELEF, ENPUSULTUP, ENPFHULTUP, ENPNROSOCI
FROM GXTRJDTA.TDGENP;
