SELECT * FROM GXsegdta.TSGNUM WHERE SGNUMOBJ = 'TBQHBL'; 

INSERT INTO GXSEGDTA.TSGNUM
(SGNUMCOD, SGNUMOBJ, SGNUMINI, SGNUMACT, SGNUMSET, SGNUMDESC, SGNUMPRG, SGNUMUNT)
VALUES(167, 'TBQHBL', 3, 3, 'N', 'Numerador Histórico Bloqueo/Desbloqueo            ', 'SQL', 0);


INSERT INTO GXTRJDTA.TDSPRC
(PRCIDPROCE, MODIDMODUL, PRCDSPROCE, PRCESTADO, PRCUSULTUP, PRCFHULTUP, PRCGENLOG)
VALUES('PBLQ001   ', 'BQ', 'WS BLOQUEO TC TD', 'A', CURRENT USER, CURRENT TIMESTAMP, 'S');

SELECT * FROM GXTRJDTA.TDSPWS;
INSERT INTO GXTRJDTA.TDSPWS
VALUES
(
  'WSJVTRJ008', --- NOMBRE DEL SERVICIO
  'SERVICIO PARA BLOQUEAR O DESBLOQUEAR TARJETAS',
  'http://',
  '10.254.102.16',  ---  IP PRODUCCIÓN
  '',
  8080,  ---   PUERTO PRODUCIÓN
  '/WSJVTRJ008/webresources/', --- URL APP PRODUCIÓN
  'bloqueoTarjetas', --- URL APP PRODUCIÓN
  0,
  0,
  'A',
  CURRENT USER,  --- USUARIO ACTUALIZACION
  CURRENT TIMESTAMP,
  ' ',
  0,
  '          ',
  '',
  0,
  0
);

 SELECT * FROM GXTRJDTA.TDSDWS WHERE PWSIDWEBS =  'WSJVTRJ008'; 
INSERT INTO GXTRJDTA.TDSDWS
VALUES
(
  'WSJVTRJ008',
  1,
  '10.212.134.51',  --- IP USUARIO HABILITADO
  1020,  --- ENTIDAD 
  0,
  1,
  'WSUSER', ---USUARIO HABILITADO DEL SERVICIO
  CURRENT USER, --- USUARIO ACTUALIZACION
  CURRENT TIMESTAMP
);

SELECT * FROM GXTRJDTA.TENECX;

10.212.134.32
INSERT INTO GXTRJDTA.TENECX
(ECXCODENT, ECXIDCONEX, ECXDSCCONE, 
ECXBADTOIP, ECXBADTOUS, ECXBADTPAS, ECXSERVPRO,
 ECXSERVPO, ECXSERVIP, ECXSERVUS, ECXSERVPAS, 
ECXUSULTUP, ECXFHULTUP, ECXFRECUEN, ECXHORADES,
 ECXHORAHAS, ECXURLCONE, ECXDRIVER, 
ECXBABIBLD, ECXUSUPROC, ECXDIAHAB, 
ECXTIMEOUT, ECXDOMINIO)
VALUES
(
  9000,--- CODIGO ENTIDAD UTILIZADO POR LA ENTIDAD O DE FORMA INTERNA
  'AS400WS                    ',
  'Datos de conexion Usuario WS',
  '10.11.254.184',  ---- IP AS400 PRODUCCIÓN
  'XXXXXX', ------ USUARIO AS400 PRODUCCIÓN DEL SERVICIO PARA CONTINENTAL
  'XXXXXX', --- PASS CIFRADO CON BepCypherUI 
  '               ',
  '               ',
  '               ',
  '          ',
  '',
  CURRENT USER, --- USUARIO ACTUALIZACION
  CURRENT TIMESTAMP,
  ' ',
  '        ',
  '        ',
  'jdbc:as400://10.11.254.184/;naming=system;errors=full;',  ---- MODIFICAR IP POR LA DE PRODUCCIÓN
  'com.ibm.as400.access.AS400JDBCDriver                        ',
  'gxfindta,gxopera,gxtrjdta,gxsegdta', --- BIBLIOTECAS UTILIZADAS EN EL SERVICIO SEPARADOS POR ,---
  '          ',
  ' ',
  0,
  ' '
);

INSERT INTO GXTRJDTA.TDSPWS
VALUES
(
  'PBLQ001', --- NOMBRE DEL SERVICIO
  'BLOQUEO DE TARJETAS CREDITO/DEBITO LOCAL E INTERNACIONAL',
  'http://',
  '10.11.254.221',  ---  IP PRODUCCIÓN
  '',
  8080,  ---   PUERTO PRODUCIÓN
  '/WSKBTRJ040/rest/', --- URL APP PRODUCIÓN
  'PBLQ001', --- URL APP PRODUCIÓN
  0,
  0,
  'A',
  CURRENT USER,  --- USUARIO ACTUALIZACION
  CURRENT TIMESTAMP,
  ' ',
  0,
  '          ',
  '',
  0,
  0
);
 --'10.212.134.51  '

INSERT INTO GXTRJDTA.TDSDWS
(PWSIDWEBS, DWSSECUE, DWSIPSERWS, ENTCODENT, DWSCLIENTE, DWSSUCUR, PWSUSUHAB, DWSUSULTUP, DWSFHULTUP)
VALUES('WSJVTRJ008', 2, '10.212.134.52  ', 1020, 0, 1, 'U999SARAV  ', 'U99ARIEL  ', '2022-01-25 15:41:40.087');

--Verificar en las tablas siguientes tablas:  TBlIdTBloq,TrjForBloq,TrjIdMotAu 
SELECT * FROM GXTRJDTA.TTCTRJ WHERE TRJNROTRJ = '6274310212000037' ; --> Reingeniería
SELECT * FROM GXBDBPS.TMTARAF;--> Sistema Actual
SELECT * FROM GXTRJDTA.TATAUT;-->  Cabecera Auditoria Débito 
SELECT * FROM GXTRJDTA.TATADT;--> Detalle Auditoria Débito
SELECT * FROM GXTRJDTA.TBQHBL; --> Histórico Bloqueo/Desbloqueo
SELECT * FROM GXTRJDTA.TDSSPR ;--> Seguimiento de Proceso
