SELECT COUNT(*)  FROM GXTRJDTA.TCOAUX t WHERE AUXTBL in('TDCLIENTE','TDCLIENTED','GCLIEAF','GDIREAF' )  AND AUXFEHO >= '2020-08-01-00.00.00.000000' AND AUXFEHO <= '2020-08-31-23.59.59.000000' AND   AUXEST = 'P'


SELECT *   FROM GXTRJDTA.TCOAUX  A
LEFT JOIN  GXTRJDTA.TCoEnC    B  ON  SUBSTRING(A.AUXCLAV,2,3) =  B.EnCEntAnt 
LEFT JOIN GXBDBPS.TDCLIENTE t  ON TDBINENTID =  SUBSTRING(A.AUXCLAV,2,3) 
WHERE  AUXTBL in('TDCLIENTE')     AND AUXFEHO >= '2020-08-01-00.00.00.000000' AND AUXFEHO <= '2020-08-31-23.59.59.000000'




SELECT *   FROM GXTRJDTA.TCOAUX  A
LEFT JOIN  GXTRJDTA.TCoEnC    B  ON  SUBSTRING(A.AUXCLAV,2,3) =  B.EnCEntAnt 
LEFT JOIN GXBDBPS.TDCLIENTE t  ON TDBINENTID =  SUBSTRING(A.AUXCLAV,2,3) 
WHERE  AUXTBL in('TDCLIENTED') AND AUXEST = 'P' ;  --- TDCLIENTED



SELECT count(*) FROM GXTRJDTA.TCOAUX  WHERE AUXTBL in('GCLIEAF') AND AUXEST = 'N' AND AUXFEHO <= '2021-05-17 00:00:00';



SELECT COUNT(*)   FROM GXTRJDTA.TCOAUX  A
LEFT JOIN  GXTRJDTA.TCoEnC    B  ON  SUBSTRING(A.AUXCLAV,2,3) =  B.EnCEntAnt 
LEFT JOIN GXBDBPS.GCLIEAF t  ON ENEMISO =  SUBSTRING(A.AUXCLAV,2,3) 
WHERE  AUXTBL in('GCLIEAF') AND AUXEST = 'N'AND  AUXFEHO <= '2021-05-17 00:00:00';  --- TDCLIENTED


SELECT COUNT(*)  FROM GXTRJDTA.TCOAUX  A
LEFT JOIN  GXTRJDTA.TCoEnC    B  ON  SUBSTRING(A.AUXCLAV,2,3) =  B.EnCEntAnt 
LEFT JOIN GXBDBPS.GCLIEAF t  ON ENEMISO =  SUBSTRING(A.AUXCLAV,2,3) 
WHERE  AUXTBL in('GDIREAF') AND AUXEST = 'N'AND  AUXFEHO <= '2021-05-17 00:00:00';  --- TDCLIENTED     



