	
Select * FROM GXFINDTA.TCMCAT;
	Select * FROM GXFINDTA.TCMCDF;
	Select * FROM GXFINDTA.TCMCLI;
	Select * FROM GXFINDTA.TCMSUC;
	Select * FROM GXFINDTA.TCMSER;
	Select * FROM GXFINDTA.TCMMAR;
	Select * FROM GXFINDTA.TCMCN;
	Select * FROM GXFINDTA.TCMTLI;
	Select * FROM GXFINDTA.TCMLIQ;
	Select * FROM GXFINDTA.TCMPR;
	Select * FROM GXFINDTA.TCMSPR;
	Select * FROM GXFINDTA.TCCNA;
	Select * FROM GXFINDTA.TCMDIR;
	Select * FROM GXFINDTA.TCMTDI;
	Select * FROM GXFINDTA.TCMDIS;
	Select * FROM GXFINDTA.TCMIMP;
	Select * FROM GXFINDTA.TCMTEN;
	Select * FROM GXFINDTA.TCMTS ;
