--------------------------------= PCON003-------------------------------------------------

SELECT count(*) FROM GXTRJDTA.TCOAUX WHERE AUXTBL ='TMTARAF'  AND AUXEST = 'P' ;--AND AUXCLAV ='6274313070012656                                  ';


SELECT count(*) FROM GXTRJDTA.TTCTRJ t  WHERE TRJFHULTUP >=  '2021-05-17 00:00:00';


SELECT * FROM   GXTRJDTA.TCOAUX t left JOIN GXTRJDTA.TTCTRJ  ON  t.AUXCLAV  = TRJNROTRJ WHERE  t.AUXEST = 'N' ;--AND AUXCLAV ='6274313070012656    TRJFHULTUP >=  '2021-05-17 00:00:00'                               ';


SELECT * FROM GXBDBPS.TMTARAF t ;

SELECT cOUNT(*) FROM   GXTRJDTA.TCOAUX t left JOIN GXBDBPS.TMTARAF t2  ON  t.AUXCLAV  = MTNUMTA   WHERE AUXTBL ='TMTARAF'  AND MTNUMTA IS NULL  AND AUXEST = 'N';   ---- VERIFICA SI EXISTE EN TMTARAF 




-- a.*, b.MTNUMTA ,b.ENEMISO , c.ENCENTACT ,c.ENCENTANT
SELECT Count(*) FROM   GXTRJDTA.TCOAUX A 
left JOIN GXBDBPS.TMTARAF B  ON  A.AUXCLAV  = MTNUMTA  
LEFT JOIN GXTRJDTA.TCoEnC  C ON C.EnCEntAnt= B.ENEMISO 
WHERE A.AUXTBL ='TMTARAF'  AND A.AUXEST = 'N'  AND ENCENTANT IS NULL AND NOT MTNUMTA IS null  ;   --------verifica si hay relacion en TCoEnC


SELECT  count(*) FROM   GXTRJDTA.TCOAUX A 
left JOIN GXBDBPS.TMTARAF B  ON  A.AUXCLAV  = MTNUMTA  
LEFT JOIN GXTRJDTA.TCoEnC  C ON C.EnCEntAnt= B.ENEMISO 
LEFT JOIN GXBDBPS.TBINEAF D ON D.ENEMISO =B.ENEMISO  AND B.BIBINES = D.BIBINES 
WHERE A.AUXTBL ='TMTARAF'  AND A.AUXEST = 'N'   AND NOT MTNUMTA IS NULL AND D.ENEMISO IS NULL ;  --------verifica si hay relacion en TBINEAF

SELECT a.AUXCLAV, b.MTNUTAA , c.EnCEntAnt,d.ENEMISO ,e.ENEMISO,FROM   GXTRJDTA.TCOAUX A 
left JOIN GXBDBPS.TMTARAF B  ON  A.AUXCLAV  = MTNUMTA  
LEFT JOIN GXTRJDTA.TCoEnC  C ON C.EnCEntAnt= B.ENEMISO 
LEFT JOIN GXBDBPS.TBINEAF D ON D.ENEMISO =B.ENEMISO  AND B.BIBINES = D.BIBINES 
LEFT JOIN GXBDBPS.TAFINAF E ON E.ENEMISO =B.ENEMISO  AND B.BIBINES = E.BIBINES  AND B.AFAFINI =E.AFAFINI 
WHERE A.AUXTBL ='TMTARAF'  AND A.AUXEST = 'N'   AND NOT MTNUMTA IS NULL  AND NOT  D.ENEMISO IS NULL  AND E.ENEMISO  IS NULL --------verifica si hay relacion en TAFINAF

SELECT a.AUXCLAV, b.MTNUTAA , c.EnCEntAnt,d.ENEMISO ,e.ENEMISO,B.CENUMDO ,F.CENUMDO  FROM   GXTRJDTA.TCOAUX A 
left JOIN GXBDBPS.TMTARAF B  ON  A.AUXCLAV  = MTNUMTA  
LEFT JOIN GXTRJDTA.TCoEnC  C ON C.EnCEntAnt= B.ENEMISO 
LEFT JOIN GXBDBPS.TBINEAF D ON D.ENEMISO =B.ENEMISO  AND B.BIBINES = D.BIBINES 
LEFT JOIN GXBDBPS.TAFINAF E ON E.ENEMISO =B.ENEMISO  AND B.BIBINES = E.BIBINES  AND B.AFAFINI =E.AFAFINI 
LEFT JOIN GXBDBPS.GCLIEAF F ON F.ENEMISO =B.ENEMISO  AND F.CETIPOD = B.CETIPOD  AND F.CENUMDO = B.CENUMDO 
WHERE A.AUXTBL ='TMTARAF'  AND A.AUXEST = 'N'   AND NOT B.MTNUMTA IS NULL  AND NOT  D.ENEMISO IS NULL  AND NOT E.ENEMISO  IS NULL AND F.CENUMDO IS NULL  --------verifica si hay relacion en TAFINAF




