SELECT * FROM  GXTRJDTA.TTCCTA WHERE CTAIDTPDOC = 'CIP' AND CTANRODOC='3794955';
SELECT * FROM CCORREA.TTCCtD;
SELECT * FROM GXTRJDTA.TCoEnC;


SELECT *  /*SUBSTRING(AUXCLAV,1,4) ENTIDAD ,SUBSTRING(AUXCLAV,5,3) tipodoc,SUBSTRING(AUXCLAV,8,15)nrodoc, AUXTBL , AUXACCI , AUXEST */FROM  CCORREA.TCOAUX  
INNER JOIN  CCORREA.TTCCTA ON CTANRODOC =SUBSTRING(AUXCLAV,5,15) where AUXTBL = 'GDIREAF' 


UPDATE   GXTRJDTA.tcoaux SET AUXEST = 'N';


SELECT * FROM GXFINDTA.TCLPRC;


SELECT * FROM GXTRJDTA.TTCCDF WHERE CTAIDCTA =41400000026 ;

select COUNT(*) from LIBCLEA.tswaut where  AUTTRXFCHC='20210113' AND AUTESTCLE = 'N';

SELECT * FROM GXFINDTA.CCASI21 ;

SELECT  * from LIBCLEA.TCLMOV WHERE MOVFPRO  ='20210113' AND SERCODI = 'REDPAG '; 




