----========================================================= PCON023=================================================================
SELECT A.CTAIDCTA  , B.MCNUMCT  FROM GXTRJDTA.TTCCta A left JOIN GXBDBPS.TMCTAAF B ON a.CTAIDCTA  = b.MCNUMCT ;




SELECT MCNUMCT ,MCNUMDO,MCTIPOD,MCTIPOC,MCEMISO,MCAFINI,MCBINES,MCFUVTO,MCFEUMO,MCFEUPG,MCFUCIE,MCFEALT,MCFEBAJ,MCSTATS FROM GXBDBPS.TMCTAAF WHERE MCNUMCT=  20110500050; --ttcta

SELECT MCNUMCT, MCFORPG,MCTIPCB,MCCTABC,MCTIPPG,MCPORPG,MCDIAMO,MCSALMO,MCPAGMI,MCSALPM  FROM GXBDBPS.TMCTAAF WHERE MCNUMCT=  20110500050; --ttccdf

SELECT MCNUMCT,MCLIMCO  FROM GXBDBPS.TMCTAAF WHERE MCNUMCT=  20110500050;--tmctaaf




SELECT * FROM GXTRJDTA.TTCCta WHERE CTAIDCTA= 20110500050;

SELECT * FROM GXTRJDTA.TTCCDF WHERE CTAIDCTA= 20110500050;

SELECT*   FROM GXTRJDTA.TTCCLC WHERE CTAIDCTA= 20110500050;



SELECT A.CTAIDCTA  , B.MCNUMCT  FROM GXTRJDTA.TTCCDF A left JOIN GXBDBPS.TMCTAAF B ON a.CTAIDCTA  = b.MCNUMCT ;

SELECT * FROM GXTRJDTA.TDSPrc WHERE MODIDMODUL = 'CO';


--=====================================pcon009===================================================================================
SELECT * FROM GXBDBPS.TMCTAAF A  
--INNER JOIN GXBDBPS.TAFINAF B ON B.ENEMISO =A.MCAFINI AND B.BIBINES = A.MCBINES AND B.AFAFINI =A.MCAFINI 
--INNER JOIN GXTRJDTA.TCOENC  C ON C.ENCENTANT = A.MCEMISO 
--INNER JOIN GXTRJDTA.TCOEAC D  ON D.EACEntAct = C.EnCEntAct AND D.EACEntAnt = A.MCEMISO 
--INNER JOIN GXTRJDTA.TDGAFI E ON C.EnCEntAct = E.ENTCODENT  AND E.AFICODAFI =D.EACAFIACT
INNER JOIN GXTRJDTA.TTCCTA F ON F.CTAIDCTA  = A.MCNUMCT;



SELECT c(* FROM GXBDBPS.TMCTAAF ORDER BY MCNUMCT ;


SELECT * FROM GXBDBPS.TAFINAF ;

SELECT * FROM GXTRJDTA.tDGAFI;

SELECT * FROM GXTRJDTA.TTCCTA;

SELECT * FROM GXTRJDTA.TDGMON;
SELECT * FROM GXTRJDTA.TTCCDF   WHERE CDFFHULTUP > '2021-04-27 00:00:00';

SELECT * FROM GXTRJDTA.TTCCDF   WHERE CTAIDCTA =20120500012 ;
SELECT * FROM GXTRJDTA.TTCCLC   WHERE CTAIDCTA =20120500012;
SELECT * FROM GXBDBPS.TMCTAAF WHERE MCNUMCT = 20120500012;



SELECT count(*) FROM GXTRJDTA.TTCCLC WHERE CLCFHULTUP > '2021-04-27 00:00:00';

--==============================pcon044 =====================================


SELECT * FROM GXTRJDTA.TDGEOP t ;--  WHERE EOPNRODOC = '2931438';


SELECT * FROM GXBDBPS.TECTAAF t WHERE ECNOMBR LIKE '%RUTH%' ;--WHERE ENEMISO = '020' AND ECCODIG ='CIP' ;

SELECT * FROM GXBDBPS.TMANENCTA t2 WHERE MECPID = '5139577     ';
