
SELECT B.BIENROTRAB, b.BIEFHTRAEM ,B.BIECNTAFEC ,B.BIEESTADO ,B.BIECNTPEMB, B.BIELOTEPLA  ,B.BIECNTFINU, B.BIECNTINIS, B.BiECntIniC ,S.STKIDSTOCK ,S.STKCNTSTK ,L.LOTCANTIDA ,L.LOTUSULTUP 
FROM  GXTRJDTA.TSTBIE B 
INNER JOIN   GXTRJDTA.TSTSTK S ON S.STKIDSTOCK = b.BiEStockPl 
INNER JOIN GXTRJDTA.TSTLOT L ON L.STKIDSTOCK =  S.STKIDSTOCK 
WHERE b.BIENROTRAB  = '20200507_1020_1' AND L.LOTNROLOTE  = 1 AND BIEFHTRAEM ='2020-05-07 09:20:49';

SELECT  BIENROTRAB, BIEFHTRAEM  ,BiECntAfec ,  BiEEstado , BiECntPEmb,BIECNTFINU   FROM   GXTRJDTA.TSTBIE  WHERE BIESTOCKPL ='PRUEBA02B'        


SELECT BIENROTRAB,  BiECntRetB , BieCntAIng,BieCntFinU,BieCntRech,BIEESTADO ,BiECntPEmb,BIESTOCKPL,BiECntPEmb     FROM   GXTRJDTA.TSTBIE WHERE  BIENROTRAB  = '20200412_1020_1'

SELECT BIENROTRAB,BIEFHTRAEM, BEDCntRetB ,BEDCntAIng , BEDCntFinU,BEDCntRech  FROM  GXTRJDTA.TSTBED 

SELECT  STKIDSTOCK , STKDSSTOCK , STKCNTSTK FROM  GXTRJDTA.TSTSTK WHERE STKIDSTOCK = 'PRUEBA02B' 

SELECT STKIDSTOCK ,LOTNROLOTE, LOTCANTIDA FROM GXTRJDTA.TSTLOT WHERE STKIDSTOCK = 'PRUEBA02B'   

/*SELECT  FROM  GXTRJDTA.TSTBIE WHERE BIEESTADO  = 'P'*/


