
    SELECT * FROM GXTRJDTA.TDSDWS WHERE  PWSIDWEBS IN ('WSJVTRJ004') ;
   

    select * from gxtrjdta.TDSDPS; WHERE PASIDPARSI = 'WSLIMHR' AND DPSAGRUP = 'WSJVTRJ004';
   
   -- VERFICAR SI EXISTEN 
   SELECT * FROM GXTRJDTA.TDSPWS WHERE PWSIDWEBS  IN ('PCLR036   ','PCLR052   ') ;
   
   
   
   -- EN CASO DE QUE NO EXISTAN INSERTAR 
  
 INSERT INTO GXTRJDTA.TDSPWS
(PWSIDWEBS, PWSDSWEBS, PWSPROTOCO, PWSIPSERWS, PWSDOMINIO, PWSPUERTO, PWSDIREC, PWSPROGRAM, PWSLIMREG, PWSCNTPET, PWSINTEXT, PWSUSULTUP, PWSFHULTUP, PWSPROPWS, PWSCODENT, PWSUSUTOKN, PWSPASTOKN, PWSTIMEOUT, PWSTEPETIC)
VALUES('PCLR036   ', 'Obtiene Impuestos                                           ', 'http://        ', '10.11.254.221'        , '                                                            ', 8080, '/WSKBFIN001/rest              ', 'PCLR036             ', 100, 50, 'A', CURRENT USER , CURRENT timestamp, ' ', 0, '          ', '', 0, 0);
INSERT INTO GXTRJDTA.TDSPWS
(PWSIDWEBS, PWSDSWEBS, PWSPROTOCO, PWSIPSERWS, PWSDOMINIO, PWSPUERTO, PWSDIREC, PWSPROGRAM, PWSLIMREG, PWSCNTPET, PWSINTEXT, PWSUSULTUP, PWSFHULTUP, PWSPROPWS, PWSCODENT, PWSUSUTOKN, PWSPASTOKN, PWSTIMEOUT, PWSTEPETIC)
VALUES('PCLR052   ', 'Verifica si existe cupon                                    ', 'http://        ', '10.11.254.221  ', '                                                            ', 8080, '/WSKBFIN002/rest              ', 'PCLR052             ', 100, 50, 'A',  CURRENT USER, CURRENT timestamp, ' ', 0, '          ', '', 0, 0);
 
 -- VERFICAR SI EXISTEN 
SELECT * FROM GXTRJDTA.TDSPrc WHERE PRCIDPROCE IN ('PCON036   ','PCON037   ' );


   -- EN CASO DE QUE NO EXISTAN INSERTAR 
INSERT INTO GXTRJDTA.TDSPRC
(PRCIDPROCE, MODIDMODUL, PRCDSPROCE, PRCESTADO, PRCUSULTUP, PRCFHULTUP, PRCGENLOG)
VALUES('PCON036   ', 'CO', 'ACTUALIZACION MOVIMIENTO DE PAGOS ESPECAL         ', 'A', CURRENT USER , CURRENT timestamp, 'N');
INSERT INTO GXTRJDTA.TDSPRC
(PRCIDPROCE, MODIDMODUL, PRCDSPROCE, PRCESTADO, PRCUSULTUP, PRCFHULTUP, PRCGENLOG)
VALUES('PCON037   ', 'CO', 'CONVIVENCIA MOV. ESPESIALES Y PAGOS               ', 'A', CURRENT USER , CURRENT timestamp, 'N');




SELECT * FROM gx