SELECT * FROM GXTRJDTA.TDSPrc;--WHERE MODIDMODUL  ='CO';

UPDATE GXTRJDTA.TDSPrc SET PRCESTADO = 'A' WHERE MODIDMODUL  ='CO' AND PRCIDPROCE  <> 'PCON013';

SELECT * FROM GXTRJDTA.TCOAUX WHERE AUXTBL = 'TDEMIS'; 

UPDATE GXTRJDTA.TCOAUX SET AUXEST = 'A' WHERE AUXTBL = 'TDEMIS';


SELECT * FROM GXBDBPS.TDEMIS;

SELECT * FROM GXTRJDTA.TTDEmi;

DELETE FROM GXTRJDTA.TTDEmi;
SELECT COUNT( *)  FROM SARAVLIB.TTDEMIBK ;


SELECT AUXTBL, SUBSTRING(AUXCLAV,2,3),SUBSTRING(AUXCLAV,5,6),SUBSTRING(AUXCLAV,11,1),SUBSTRING(AUXCLAV,12,1),SUBSTRING(AUXCLAV,13,12), AUXEST ,AUXACCI FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TDEMIS';

SELECT * FROM GXBDBPS.TDEMIS  INNER JOIN  GXTRJDTA.TCOAUX ON 	
SUBSTRING(TDCTANRO,1,14)   =  SUBSTRING(AUXCLAV,13,12) AND TDBINENTID =  SUBSTRING(AUXCLAV,1,4) AND TDBINNRO   =  SUBSTRING(AUXCLAV,5,6);

SELECT *FROM GXTRJDTA.TTDEMI;