SELECT  * FROM GXTRJDTA.TCOAUX WHERE AUXEST ='P' ;
SELECT  COUNT(*) FROM GXTRJDTA.TCOAUX WHERE AUXEST ='N' ;

UPDATE GXTRJDTA.TCOAUX  SET AUXEST ='N'  WHERE AUXTBL = 'TDCTA'   ;


SELECT * FROM GXTRJDTA.TCOAUX  WHERE AUXTBL = 'TMTARAF' ;