SELECT * FROM gxfindta.TCMGRU ;

SELECT * FROM gxfindta.tcmrub ;


SELECT * FROM gxfindta.TCMGEC t ;

SELECT * FROM GXTRJDTA.TDSPRC t ;

SELECT * FROM GXTRJDTA.tcmmi t ;

SELECT * FROM GXFINDTA.TCMMMD t ;

SELECT * FROM GXFINDTA.tcmapr;
SELECT * FROM GXTRJDTA.TTCCCo;

SELECT * FROM gxtrjdta.tdgbin WHERE BINCODAFI  = 503;

SELECT  * FROM GXTRJDTA.TTCTrj t WHERE TRJNROTRJ = '6274310213000671     '   ;

SELECT *  FROM gxbdbps.TMTARAF t WHERE MTNUMTA ='6274310213000671  ' ;

SELECT *  FROM gxbdbps.TMTARAF t WHERE MTNUMTA ='6274310213000671  ' ;