 SELECT * FROM GXTRJDTA.TDSPrc;
 SELECT  * FROM GXOPERA.SERVBPS;



 SELECT TPCCODCO,SERCODI,TPCMARCA,TPCORIG,TPCPROD,TPCTPTAR,TPCFPRO FROM GXFINDTA.TCLTPC where ECCCDERRCC = '21' and TPCFPRO='20201028'




SELECT COCOMER,BpsSrvCod,CCMARCA,CCMAROR,CCMARPR,CCTIPTA,CCFCHDES FROM GXBDBPS.comaexd WHERE COCOMER = 0700277 ORDER BY COCOMER, BpsSrvCod, CCMARCA, CCMAROR, CCMARPR, CCTIPTA,CCFCHDES;  -- Comision 1 



