 SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV
WHERE MOVESTA = 'A'
AND MOVCODEM = 102001 --AND MOVADMI <> 100202
AND MOVFPRO = '20201224'
AND MOVCODIS = 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA; --- Emisor CONTINENTAL 



SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV
WHERE MOVESTA = 'A'
AND MOVADMI = 102002 AND MOVCODEM <> 102001
AND MOVFPRO = '20201224'
AND MOVCODIS = 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA; -- EMISOR OTRA ENTIDADES 





-- CONTI EN SUS PROPIO CAJERO
SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV 
WHERE MOVESTA = 'A'
AND MOVADMI = 102002 AND MOVCODEM = 102001
AND MOVFPRO = '20201224'
AND MOVCODIS = 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA;-- 1.946.054.950
 
-- SACAR LAS TRX DE SUS PROPIO CAJEROS
SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV 
WHERE MOVESTA = 'A'
AND MOVADMI = 102002 AND NOT MOVCODEM = 102001
AND MOVFPRO = '20201224'
AND MOVCODIS = 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA;-- 6.197.749.751


-- OTRAS ENTIDADES COMO ADMINISTRADOR
SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV
WHERE MOVESTA = 'A'
AND MOVCODEM = 102001 AND NOT MOVADMI = 102002
AND MOVFPRO = '20201224'
AND MOVCODIS = 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA;


 SELECT MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA,SUM(MOVIMPO)
FROM GXFINDTA.TCLMOV
WHERE MOVESTA = 'A'
AND MOVCODEM = 102001 --AND MOVADMI <> 100202
AND MOVFPRO = '20201224'
AND MOVCODIS <> 'ATM'
GROUP BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA
ORDER BY MOVCODEM,MOVFPRO,MOVCODIS,MOVADMI,MOVFCRE,MOVTPTA,MOVFPGO,MOVPGON,MOVESTA; 





UPDATE GXTRJDTA.TDGECO SET ECOIVAINCL='N' WHERE ENSIDSERV='COMPRA';
UPDATE GXTRJDTA.TDGECO SET ECOVALCOMI=0.73 WHERE ENTCODENT=1020;
UPDATE gxfindta.tclprc SET PRCCOD = 'PCLR054' where prcparm in ('CAIN','CAOU','GIRO');


SELECT *  FROM GXTRJDTA.TTCTrj WHERE TrjValHas = 202012 

SELECT cOUNT(*)FROM GXTRJDTA.TTDEMI WHERE EmiFecVenc = 202012 AND EmiVencida = 'S' AND EmiVigente = 'N' ;
SELECT * FROM GXTRJDTA.TTDEMI WHERE EmiFecVenc = 202012 ;



 UPDATE  GXTRJDTA.TTCTrj SET TrjVencida = 'N'   WHERE TrjValHas = 202012;